using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class CppWinRT_AppPass2 : CppWinRT_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n//------------------------------------------------------------------------------\r\n\r\n");
		if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.PrecompiledHeaderFile));
			Write("\"\r\n");
		}
		Write("#include <windows.h>\r\n");
		foreach (string neededLocalXamlHeaderFile in base.Model.NeededLocalXamlHeaderFiles)
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(neededLocalXamlHeaderFile));
			Write("\"\r\n");
		}
		Write("\r\n#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION\r\nextern \"C\" __declspec(dllimport) int __stdcall IsDebuggerPresent();\r\n#endif\r\n\r\n");
		if (base.ProjectInfo.VSDesignerDontLoadAsDll)
		{
			Write("#define _VSDESIGNER_DONT_LOAD_AS_DLL\r\n");
		}
		Write("\r\n#if (defined(_M_IX86) || defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64)) && !defined(_VSDESIGNER_DONT_LOAD_AS_DLL)\r\n#if defined(_M_IX86)\r\n#pragma comment(linker, \"/EXPORT:DllGetActivationFactory=_VSDesignerDllGetActivationFactory@8,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:DllCanUnloadNow=_VSDesignerCanUnloadNow@0,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:VSDesignerDllMain=_VSDesignerDllMain@12,PRIVATE\")\r\n#elif defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64)\r\n#pragma comment(linker, \"/EXPORT:DllGetActivationFactory=VSDesignerDllGetActivationFactory,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:VSDesignerCanUnloadNow,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:VSDesignerDllMain,PRIVATE\")\r\n#endif\r\n\r\nextern \"C\"\r\n{\r\n    int __stdcall _DllMainCRTStartup(void* hinstDLL, unsigned long fdwReason, void** lpvReserved);\r\n\r\n    int __stdcall VSDesignerDllGetActivationFactory(void* classId, void** factory)\r\n    {\r\n        return WINRT_GetActivationFactory(classId, factory);\r\n    }\r\n\r\n    int __stdcall VSDesignerCanUnloadNow()\r\n    {\r\n        return WINRT_CanUnloadNow();\r\n    }\r\n\r\n    int __stdcall VSDesignerDllMain(void* hinstDLL, unsigned long fdwReason, void** lpvReserved)\r\n    {\r\n        return _DllMainCRTStartup(hinstDLL, fdwReason, lpvReserved);\r\n    }\r\n}\r\n\r\n#endif // (defined(_M_IX86) || defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64))) && !defined(_VSDESIGNER_DONT_LOAD_AS_DLL)\r\n\r\n#ifndef DISABLE_XAML_GENERATED_MAIN\r\nint __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)\r\n{\r\n");
		if (base.ProjectInfo.IsWin32App)
		{
			Write("    winrt::init_apartment(winrt::apartment_type::single_threaded);\r\n");
		}
		else
		{
			Write("    winrt::init_apartment();\r\n");
		}
		Write("    ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::Application::Start(\r\n        [](auto&&)\r\n        {\r\n            ::winrt::make<");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<PageDefinition>.Projection(base.Model.CodeInfo.ClassName.Namespace + ".implementation." + base.Model.CodeInfo.ClassName.ShortName)));
		Write(">();\r\n        });\r\n\r\n    return 0;\r\n}\r\n#endif\r\n");
		return base.GenerationEnvironment.ToString();
	}
}
