using System.CodeDom.Compiler;
using System.Linq;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class CSharpPagePass1 : CSharp_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		foreach (FileNameAndChecksumPair xamlFileFullPathAndCheckSum in base.Model.XamlFileFullPathAndCheckSums)
		{
			Write("#pragma checksum \"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.FileName));
			Write("\" \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.Model.ChecksumAlgorithmGuid));
			Write("\" \"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.Checksum));
			Write("\"\r\n");
		}
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n\r\nnamespace ");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.Namespace));
		Write("\r\n{\r\n    partial class ");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write(" : global::");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.BaseTypeName));
		Write("\r\n    {\r\n\r\n");
		Output_xProperties();
		Write("\r\n");
		Output_FieldDefinitions();
		Write("        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        private bool _contentLoaded;\r\n\r\n");
		Output_InitializeComponent();
		Write("\r\n");
		if (base.Model.CodeInfo.BindStatus != BindStatus.None)
		{
			Output_BindingsHeader();
		}
		Write("    }\r\n}\r\n\r\n");
		return base.GenerationEnvironment.ToString();
	}

	private void Output_InitializeComponent()
	{
		string loadComponentUri = base.Model.GetLoadComponentUri(base.Model.CodeInfo.PriIndexName, base.Model.CodeInfo.BaseApparentRelativePath);
		Write("        /// <summary>\r\n        /// InitializeComponent()\r\n        /// </summary>\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
		Write("\r\n        public void InitializeComponent()\r\n        {\r\n");
		if (base.Model.CodeInfo.PerXamlFileInfo.Count > 1)
		{
			Write("            this.InitializeComponent(null);\r\n        }\r\n\r\n        /// <summary>\r\n        /// InitializeComponent()\r\n        /// </summary>\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
			Write("\r\n        public void InitializeComponent(global::System.Uri resourceLocator)\r\n        {\r\n");
		}
		Write("            if (_contentLoaded)\r\n                return;\r\n\r\n            _contentLoaded = true;\r\n\r\n");
		if (base.Model.XProperties.Any())
		{
			Write("        InitializeXProperties();\r\n");
		}
		if (base.Model.CodeInfo.PerXamlFileInfo.Count > 1)
		{
			Write("            if (resourceLocator == null)\r\n            {\r\n                resourceLocator = new global::System.Uri(\"");
			Write(base.ToStringHelper.ToStringWithCulture(loadComponentUri));
			Write("\");\r\n            }\r\n");
		}
		else
		{
			Write("            global::System.Uri resourceLocator = new global::System.Uri(\"");
			Write(base.ToStringHelper.ToStringWithCulture(loadComponentUri));
			Write("\");\r\n");
		}
		string objectToConvert = (base.ProjectInfo.IsLibrary ? "Nested" : "Application");
		if (!string.IsNullOrEmpty(base.Model.CodeInfo.XamlComponentResourceLocation))
		{
			Write("            ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Application")));
			Write(".LoadComponent(this, resourceLocator, ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Controls.Primitives.ComponentResourceLocation")));
			Write(".");
			Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.XamlComponentResourceLocation));
			Write(");\r\n");
		}
		else
		{
			Write("            ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Application")));
			Write(".LoadComponent(this, resourceLocator, ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Controls.Primitives.ComponentResourceLocation")));
			Write(".");
			Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
			Write(");\r\n");
		}
		Write("        }\r\n\r\n        partial void UnloadObject(");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.DependencyObject")));
		Write(" unloadableObject);\r\n");
	}

	private void Output_FieldDefinitions()
	{
		Write("#pragma warning disable 0169    //  Proactively suppress unused/uninitialized field warning in case they aren't used, for things like x:Name\r\n#pragma warning disable 0649\r\n");
		foreach (FieldDefinition fieldDeclaration in base.Model.CodeInfo.FieldDeclarations)
		{
			Write("        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n");
			if (fieldDeclaration.IsDeprecated)
			{
				Write("#pragma warning disable 0618  //   Warning on Deprecated usage\r\n");
			}
			Write("        ");
			Write(base.ToStringHelper.ToStringWithCulture(fieldDeclaration.FieldModifier));
			Write(" global::");
			Write(base.ToStringHelper.ToStringWithCulture(fieldDeclaration.FieldTypeName));
			Write(" ");
			Write(base.ToStringHelper.ToStringWithCulture(fieldDeclaration.FieldName));
			Write("; \r\n");
			if (fieldDeclaration.IsDeprecated)
			{
				Write("#pragma warning restore 0618\r\n");
			}
		}
		Write("#pragma warning restore 0649\r\n#pragma warning restore 0169\r\n");
	}

	private void Output_BindingsHeader()
	{
		Write("        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        private interface I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_Bindings\r\n        {\r\n            void Initialize();\r\n            void Update();\r\n            void StopTracking();\r\n            void DisconnectUnloadedObject(int connectionId);\r\n        }\r\n\r\n        private interface I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_BindingsScopeConnector\r\n        {\r\n            ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize(base.WeakReferenceTypeName)));
		Write(" Parent { get; set; }\r\n            bool ContainsElement(int connectionId);\r\n            void RegisterForElementConnection(int connectionId, ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Markup.IComponentConnector")));
		Write(" connector);\r\n        }\r\n#pragma warning disable 0169    //  Proactively suppress unused field warning in case Bindings is not used.\r\n#pragma warning disable 0649\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        private I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_Bindings Bindings;\r\n#pragma warning restore 0649\r\n#pragma warning restore 0169\r\n");
	}

	private void Output_xProperties()
	{
		if (base.Model.XProperties.Any())
		{
			Write("        partial void InitializeXProperties();\r\n\r\n");
		}
		foreach (xProperty xProperty in base.Model.XProperties)
		{
			Write("        // ");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.CodegenComment));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        private global::");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
			Write(" _");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write(";\r\n");
			if (!xProperty.IsReadOnly)
			{
				Write("        /// <summary>\r\n        /// ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write(" - changed handler for ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write("\r\n        /// </summary>\r\n        ");
				Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
				Write("\r\n        public event ");
				Write(base.ToStringHelper.ToStringWithCulture(PrependNamespace("PropertyChangedEventHandler")));
				Write(" ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write(";\r\n");
			}
			Write("        /// <summary>\r\n        /// ");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write("\r\n        /// </summary>\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
			Write("\r\n        public global::");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
			Write(" ");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write("\r\n        {\r\n            get { return _");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write("; }\r\n");
			if (!xProperty.IsReadOnly)
			{
				Write("            set\r\n            {\r\n                if (_");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write(" != value)\r\n                {\r\n                    _");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write(" = value;\r\n                    if (");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write(" != null)\r\n                    {\r\n                        ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write("(this, new global::");
				Write(base.ToStringHelper.ToStringWithCulture(PrependNamespace("PropertyChangedEventArgs(\"" + xProperty.Name + "\")")));
				Write(");\r\n                       \r\n                    }\r\n                }\r\n            }\r\n");
			}
			Write("        }\r\n\r\n");
		}
	}
}
