using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class MoComCppTypeInfoPass1 : CppCX_CodeGenerator<TypeInfoDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n#pragma once\r\n#include <collection.h>\r\n\r\nnamespace XamlTypeInfo\r\n{\r\n    namespace InfoProvider\r\n    {\r\n");
		if (base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("        ref class XamlActivatableType sealed\r\n        {\r\n        internal:\r\n            typedef ::Platform::Object^ (*ActivatorFn)();\r\n            property ActivatorFn Activator;\r\n            XamlActivatableType();            \r\n\r\n        public:\r\n            ::Platform::Object^ ActivateInstance();\r\n        };\r\n\r\n");
		}
		Write("        ref class XamlTypeInfoProvider sealed\r\n        {\r\n            struct CriticalSection\r\n            {\r\n                CriticalSection()\r\n                {\r\n                    InitializeCriticalSection(&criticalSection);\r\n                }\r\n\r\n                ~CriticalSection()\r\n                {\r\n                    DeleteCriticalSection(&criticalSection);\r\n                }\r\n\r\n                struct AutoLock\r\n                {\r\n                    AutoLock(LPCRITICAL_SECTION criticalSection)\r\n                        : pCriticalSection(criticalSection)\r\n                    {\r\n                        EnterCriticalSection(criticalSection);\r\n                    }\r\n\r\n                    ~AutoLock()\r\n                    {\r\n                        LeaveCriticalSection(pCriticalSection);\r\n                    }\r\n\r\n                private:\r\n                    LPCRITICAL_SECTION pCriticalSection{ nullptr };\r\n                };\r\n\r\n                AutoLock Lock()\r\n                {\r\n                    return AutoLock(&criticalSection);\r\n                }\r\n\r\n            private:\r\n                CRITICAL_SECTION criticalSection;\r\n            };\r\n\r\n        public:\r\n            ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ GetXamlTypeByName(::Platform::String^ typeName);\r\n            ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ GetXamlTypeByType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName t);\r\n");
		if (!base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ GetMemberByLongName(::Platform::String^ longMemberName);\r\n");
		}
		if (!base.ProjectInfo.GenerateProviderCode || !base.ProjectInfo.GenerateProviderCode)
		{
			Write("            void AddOtherProvider(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^ otherProvider);\r\n");
		}
		Write("\r\n        private:\r\n            CriticalSection _xamlTypesCriticalSection;\r\n            CriticalSection _xamlMembersCriticalSection;\r\n            std::map<::Platform::String^, ::Platform::WeakReference> _xamlTypes;\r\n            std::map<::Platform::String^, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember^> _xamlMembers;\r\n            ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ CreateXamlType(::Platform::String^ typeName);\r\n            ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember^ CreateXamlMember(::Platform::String^ longMemberName);\r\n");
		if (base.ProjectInfo.GenerateOtherProvidersForCX)
		{
			Write("\r\n            ::Platform::Collections::Vector<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^>^ _otherProviders;\r\n            property ::Platform::Collections::Vector<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^>^ OtherProviders\r\n            {\r\n                ::Platform::Collections::Vector<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^>^ get();\r\n            }\r\n\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ CheckOtherMetadataProvidersForName(::Platform::String^ typeName);\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ CheckOtherMetadataProvidersForType(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName t);\r\n");
		}
		if (base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Globalize(base.ProjectInfo.XamlTypeInfoReflectionNamespace)));
			Write("::ReflectionXamlMetadataProvider^ _ReflectionProvider;\r\n            property ");
			Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Globalize(base.ProjectInfo.XamlTypeInfoReflectionNamespace)));
			Write("::ReflectionXamlMetadataProvider^ ReflectionProvider\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Globalize(base.ProjectInfo.XamlTypeInfoReflectionNamespace)));
			Write("::ReflectionXamlMetadataProvider^ get();\r\n            }\r\n\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ GetCachedType(::Platform::String^ typeName);\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ AddCachedType(::Platform::String^ typeName, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ reflectionType);\r\n\r\n        internal:\r\n            XamlActivatableType^ GetActivatableTypeForTypeName(::Platform::String^ typeName);\r\n");
		}
		Write("        };\r\n\r\n");
		if (!base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("        ref class XamlSystemBaseType sealed : public ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType\r\n        {\r\n        internal:\r\n            XamlSystemBaseType(::Platform::String^ name);\r\n\r\n        public:\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ BaseType \r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ ContentProperty \r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ get();\r\n            }\r\n\r\n            virtual property ::Platform::String^ FullName\r\n            {\r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property ::Platform::String^ Name\r\n            {\r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property bool IsArray\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsCollection\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsConstructible\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsDictionary\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsMarkupExtension\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsEnum\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsSystemType\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsBindable\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ ItemType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ KeyType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ BoxedType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName UnderlyingType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName get();\r\n            }\r\n\r\n            virtual ::Platform::Object^ ActivateInstance();\r\n            virtual ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ GetMember(::Platform::String^ name);\r\n            virtual void AddToVector(::Platform::Object^ instance, ::Platform::Object^ value);\r\n            virtual void AddToMap(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ value);\r\n            virtual void RunInitializer();\r\n            virtual ::Platform::Object^ CreateFromString(::Platform::String^ value);\r\n\r\n        private:\r\n            ::Platform::String^ _fullName;\r\n        };\r\n\r\n");
			string objectToConvert = CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup") + "::IXamlType";
			Write("        ref class XamlUserType sealed : public [::Platform::Metadata::RuntimeClassName] ");
			Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
			Write("\r\n        {\r\n        internal:\r\n            XamlUserType(::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ provider, ::Platform::String^ fullName, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ baseType);            \r\n\r\n        public:\r\n            // --- Interface methods ----\r\n            virtual property ::Platform::String^ FullName\r\n            {\r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property ::Platform::String^ Name\r\n            {\r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName UnderlyingType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName get();\r\n            }\r\n\r\n            virtual property bool IsSystemType\r\n            {\r\n                bool get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ BaseType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property bool IsArray \r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property bool IsCollection \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsConstructible \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsDictionary \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsMarkupExtension \r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property bool IsEnum \r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property bool IsBindable\r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ ContentProperty \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ ItemType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ KeyType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ BoxedType\r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ GetMember(::Platform::String^ name);\r\n            virtual ::Platform::Object^ ActivateInstance();\r\n            virtual void AddToMap(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ value);\r\n            virtual void AddToVector(::Platform::Object^ instance, ::Platform::Object^ value);\r\n            virtual void RunInitializer();\r\n            virtual ::Platform::Object^ CreateFromString(::Platform::String^ value);\r\n            // --- End of Interface methods\r\n\r\n            property bool IsReturnTypeStub\r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            property bool IsLocalType\r\n            {\r\n                bool get();\r\n                internal:  void set(bool value);\r\n            }\r\n\r\n        internal:\r\n            typedef ::Platform::Object^ (*ActivatorFn)();\r\n            typedef void (*AddToCollectionFn)(::Platform::Object^ instance, ::Platform::Object^ item);\r\n            typedef void (*AddToDictionaryFn)(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item);\r\n            typedef ::Platform::Object^ (*CreateFromStringFn)(::Platform::String^);\r\n            typedef ::Platform::Object^ (*StringConverterFn)(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input);\r\n\r\n            property ActivatorFn Activator;\r\n            property AddToCollectionFn CollectionAdd;\r\n            property AddToDictionaryFn DictionaryAdd;\r\n            property CreateFromStringFn CreateFromStringMethod;\r\n            property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeKind KindOfType;\r\n            property StringConverterFn FromStringConverter;\r\n\r\n            property ::Platform::String^ ContentPropertyName\r\n            {\r\n                void set(::Platform::String^ value);\r\n            }\r\n\r\n            property ::Platform::String^ ItemTypeName\r\n            {\r\n                void set(::Platform::String^ value);\r\n            }\r\n\r\n            property ::Platform::String^ KeyTypeName\r\n            {\r\n                void set(::Platform::String^ value);\r\n            }\r\n\r\n            void SetBoxedType(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ boxedType);\r\n            void AddMemberName(::Platform::String^ shortName);\r\n            void AddEnumValue(::Platform::String^ name, ::Platform::Object^ value);\r\n            uint32 CreateEnumUIntFromString(::Platform::String^ input);\r\n\r\n        private:\r\n            ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ _provider;\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ _baseType;\r\n            ::Platform::String^ _contentPropertyName;\r\n            ::Platform::String^ _itemTypeName;\r\n            ::Platform::String^ _keyTypeName;\r\n            ::Platform::String^ _fullName;\r\n            std::map<::Platform::String^, ::Platform::String^> _memberNames;\r\n            std::map<std::wstring, ::Platform::Object^> _enumValues;\r\n            bool _isArray = false;\r\n            bool _isMarkupExtension = false;\r\n            bool _isEnum = false;\r\n            bool _isBindable = false;\r\n            bool _isReturnTypeStub = false;\r\n            bool _isLocalType = false;\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ _boxedType;\r\n        };\r\n\r\n        ref class XamlMember sealed : public ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember\r\n        {\r\n        internal:\r\n            XamlMember(::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ provider, ::Platform::String^ name, ::Platform::String^ typeName);\r\n\r\n            typedef ::Platform::Object^ (*PropertyGetterFn)(::Platform::Object^ instance);\r\n            typedef void (*PropertySetterFn)(::Platform::Object^ instance, ::Platform::Object^ value);\r\n\r\n            property PropertyGetterFn Getter;\r\n            property PropertySetterFn Setter;\r\n\r\n        public:\r\n            virtual property bool IsAttachable\r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property bool IsDependencyProperty \r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property bool IsReadOnly\r\n            { \r\n                bool get();\r\n                internal: void set(bool value);\r\n            }\r\n\r\n            virtual property ::Platform::String^ Name\r\n            { \r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ Type\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ TargetType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual ::Platform::Object^ GetValue(::Platform::Object^ instance);\r\n            virtual void SetValue(::Platform::Object^ instance, ::Platform::Object^ value);\r\n\r\n        internal:\r\n            virtual property ::Platform::String^ TargetTypeName\r\n            {\r\n                void set(::Platform::String^ value);\r\n            }\r\n\r\n        private:\r\n            bool _isAttachable;\r\n            bool _isDependencyProperty;\r\n            bool _isReadOnly; \r\n            ::Platform::String^ _name;\r\n            ::Platform::String^ _targetTypeName;\r\n            ::Platform::String^ _typeName;\r\n            ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ _provider;\r\n        };\r\n");
		}
		else
		{
			Write("\r\n        ref class XamlConsolidatedType sealed : public [::Platform::Metadata::RuntimeClassName] ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType\r\n        {\r\n        internal:\r\n            XamlConsolidatedType(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ reflectionType, XamlActivatableType^ activatableType);            \r\n\r\n        public:\r\n            // --- Interface methods ----\r\n            virtual property ::Platform::String^ FullName\r\n            {\r\n                ::Platform::String^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName UnderlyingType\r\n            {\r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
			Write("::TypeName get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ BaseType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property bool IsArray \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsCollection \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsConstructible \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsDictionary \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsMarkupExtension \r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property bool IsBindable\r\n            { \r\n                bool get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ ContentProperty \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ ItemType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual property ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ KeyType \r\n            { \r\n                ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ get();\r\n            }\r\n\r\n            virtual ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ GetMember(::Platform::String^ name);\r\n            virtual ::Platform::Object^ ActivateInstance();\r\n            virtual void AddToMap(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ value);\r\n            virtual void AddToVector(::Platform::Object^ instance, ::Platform::Object^ value);\r\n            virtual void RunInitializer();\r\n            virtual ::Platform::Object^ CreateFromString(::Platform::String^ value);\r\n            // --- End of Interface methods\r\n\r\n        private:\r\n            ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ _reflectionType;\r\n            XamlActivatableType^ _activatableType;\r\n        };\r\n");
		}
		Write("    }\r\n}");
		return base.GenerationEnvironment.ToString();
	}
}
