using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class MoComCppAppPass2 : CppCX_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n//------------------------------------------------------------------------------\r\n\r\n");
		if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.PrecompiledHeaderFile));
			Write("\"\r\n");
		}
		Output_IncludeFiles_CPP();
		Write("\r\n\r\n#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION\r\nextern \"C\" __declspec(dllimport) int __stdcall IsDebuggerPresent();\r\n#endif\r\n\r\n");
		if (base.ProjectInfo.VSDesignerDontLoadAsDll)
		{
			Write("#define _VSDESIGNER_DONT_LOAD_AS_DLL\r\n");
		}
		Write("\r\n#if (defined(_M_IX86) || defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64)) && !defined(_VSDESIGNER_DONT_LOAD_AS_DLL)\r\n#if defined(_M_IX86)\r\n#pragma comment(linker, \"/EXPORT:DllGetActivationFactory=_DllGetActivationFactory@8,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:DllCanUnloadNow=_DllCanUnloadNow@0,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:VSDesignerDllMain=_VSDesignerDllMain@12,PRIVATE\")\r\n#pragma comment(linker, \"/INCLUDE:___refMTAThread\")\r\n#elif defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64)\r\n#pragma comment(linker, \"/EXPORT:DllGetActivationFactory=DllGetActivationFactory,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:DllCanUnloadNow,PRIVATE\")\r\n#pragma comment(linker, \"/EXPORT:VSDesignerDllMain,PRIVATE\")\r\n#pragma comment(linker, \"/INCLUDE:__refMTAThread\")\r\n#endif\r\n\r\nextern int __abi___threading_model;\r\n\r\nextern \"C\"\r\n{\r\n    int __stdcall _DllMainCRTStartup(void* hinstDLL, unsigned long fdwReason, void** lpvReserved);\r\n\r\n    int __stdcall VSDesignerDllMain(void* hinstDLL, unsigned long fdwReason, void** lpvReserved)\r\n    {\r\n        __abi___threading_model = _VCCORLIB_THREADING_MODEL_OVERRIDE;\r\n        return _DllMainCRTStartup(hinstDLL, fdwReason, lpvReserved);\r\n    }\r\n}\r\n\r\n#endif // (defined(_M_IX86) || defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64)) && !defined(_VSDESIGNER_DONT_LOAD_AS_DLL)\r\n\r\nvoid ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("::InitializeComponent()\r\n{\r\n    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L\"");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.GetLoadComponentUri(base.Model.CodeInfo.PriIndexName, base.Model.CodeInfo.BaseApparentRelativePath)));
		Write("\");\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::Application::LoadComponent(this, resourceLocator);\r\n\r\n#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION\r\n    UnhandledException += ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::UnhandledExceptionEventHandler(\r\n        [](::Platform::Object^ sender, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::UnhandledExceptionEventArgs^ e)\r\n        {\r\n            (void)sender; // Unused parameter\r\n            if (IsDebuggerPresent())\r\n            {\r\n                ::Platform::String^ errorMessage = e->Message;\r\n                __debugbreak();\r\n            }\r\n        });\r\n#endif\r\n}\r\n\r\n");
		if (!base.ProjectInfo.GenerateProviderCode && !base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("void  ::");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
			Write("::AddOtherProvider(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^ otherProvider)\r\n{\r\n    _AppProvider->AddOtherProvider(otherProvider);\r\n}\r\n\r\n");
		}
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("::GetXamlType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName type)\r\n{\r\n    return _AppProvider->GetXamlTypeByType(type);\r\n}\r\n\r\n");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("::GetXamlType(::Platform::String^ fullName)\r\n{\r\n    return _AppProvider->GetXamlTypeByName(fullName);\r\n}\r\n\r\n::Platform::Array<");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::XmlnsDefinition>^ ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("::GetXmlnsDefinitions()\r\n{\r\n    return ref new ::Platform::Array<");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::XmlnsDefinition>(0);\r\n}\r\n\r\n::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("::_AppProvider::get()\r\n{\r\n    if (__provider == nullptr)\r\n    {\r\n        __provider = ref new ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider();\r\n    }\r\n    return __provider;\r\n}\r\n\r\n#ifndef DISABLE_XAML_GENERATED_MAIN\r\nint __cdecl main(::Platform::Array<::Platform::String^>^ args)\r\n{\r\n    (void)args; // Unused parameter\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::Application::Start(ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::ApplicationInitializationCallback(\r\n        [](");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::ApplicationInitializationCallbackParams^ p) {\r\n            (void)p; // Unused parameter\r\n            auto app = ref new ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.ClassName.FullName)));
		Write("();\r\n        }));\r\n}\r\n#endif\r\n\r\n");
		return base.GenerationEnvironment.ToString();
	}

	private void Output_IncludeFiles_CPP()
	{
		foreach (string neededLocalXamlHeaderFile in base.Model.NeededLocalXamlHeaderFiles)
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(neededLocalXamlHeaderFile));
			Write("\"\r\n");
		}
	}
}
