using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class MoComCppAppPass1 : CppCX_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		Write("#pragma once\r\n//------------------------------------------------------------------------------\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n//------------------------------------------------------------------------------\r\n\r\n#include \"XamlTypeInfo.g.h\"\r\n\r\n");
		OutputNamespaceBegin(base.Model.CodeInfo.ClassName.Namespace);
		Write("partial ref class ");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write(" :  public ::");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Colonize(base.Model.CodeInfo.BaseTypeName)));
		Write(",\r\n    public ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMetadataProvider\r\n{\r\npublic:\r\n    void InitializeComponent();\r\n");
		if (!base.ProjectInfo.GenerateProviderCode && !base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("    void AddOtherProvider(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^ otherProvider);\r\n");
		}
		Write("    [::Windows::Foundation::Metadata::DefaultOverload]\r\n    virtual ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ GetXamlType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName type);\r\n    virtual ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType^ GetXamlType(::Platform::String^ fullName);\r\n    virtual ::Platform::Array<");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<PageDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::XmlnsDefinition>^ GetXmlnsDefinitions();\r\nprivate:\r\n    ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ __provider; \r\n    bool _contentLoaded;\r\n    property ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ _AppProvider\r\n    {\r\n        ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ get();\r\n    }\r\n};\r\n");
		OutputNamespaceEnd(base.Model.CodeInfo.ClassName.Namespace);
		return base.GenerationEnvironment.ToString();
	}
}
