using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class VisualBasicAppPass1 : VB_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		foreach (FileNameAndChecksumPair xamlFileFullPathAndCheckSum in base.Model.XamlFileFullPathAndCheckSums)
		{
			Write("#ExternalChecksum(\"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.FileName));
			Write("\", \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.Model.ChecksumAlgorithmGuid));
			Write("\", \"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.Checksum));
			Write("\")\r\n");
		}
		Write("'------------------------------------------------------------------------------\r\n' <auto-generated>\r\n'     This code was generated by a tool.\r\n'\r\n'     Changes to this file may cause incorrect behavior and will be lost if\r\n'     the code is regenerated.\r\n' </auto-generated>\r\n'------------------------------------------------------------------------------\r\n\r\nOption Strict Off\r\nOption Explicit On\r\n\r\nNamespace ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize(base.Model.CodeInfo.ClassName.Namespace)));
		Write("\r\n\r\n#If Not DISABLE_XAML_GENERATED_MAIN Then\r\nPublic Class Program\r\n\r\n    <MTAThread()> _\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
		Write("\r\n    Shared Sub Main(ByVal args() As String)\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
		Write(".Application.Start(Function(p) New Global.");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.FullName));
		Write("())\r\n    End Sub\r\n\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
		Write("\r\n    Sub Program\r\n    End Sub\r\n\r\nEnd Class\r\n#End If\r\n\r\n\r\n<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>  _\r\nPartial Class ");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("\r\n    Inherits Global.");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.BaseTypeName));
		Write("\r\n\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n    Private _contentLoaded As Boolean\r\n");
		if (!base.ProjectInfo.GenerateProviderCode && !base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("\r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
			Write("\r\n    Public Sub AddOtherProvider(otherProvider as ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Markup")));
			Write(".IXamlMetadataProvider)\r\n        _AddOtherProvider(otherProvider)\r\n    End Sub\r\n    Private Partial Sub _AddOtherProvider(otherProvider as ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Markup")));
			Write(".IXamlMetadataProvider)\r\n    End Sub\r\n\r\n");
		}
		Write("    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
		Write("\r\n    Public Sub InitializeComponent()\r\n        If _contentLoaded Then\r\n            Return\r\n        End If\r\n        _contentLoaded = true\r\n\r\n        Dim resourceLocator As New Global.System.Uri(\"");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.GetLoadComponentUri(base.Model.CodeInfo.PriIndexName, base.Model.CodeInfo.BaseApparentRelativePath)));
		Write("\")\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
		Write(".Application.LoadComponent(Me, resourceLocator)\r\n\r\n#If Debug AndAlso Not DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT Then\r\n        AddHandler Me.DebugSettings.BindingFailed,\r\n            Sub(Sender As Global.System.Object, bindingFailedArgs As ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
		Write(".BindingFailedEventArgs)\r\n                Global.System.Diagnostics.Debug.WriteLine(bindingFailedArgs.Message)\r\n            End Sub\r\n#End If\r\n\r\n#If Debug AndAlso Not DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION Then\r\n        AddHandler Me.UnhandledException,\r\n            Sub(sender As Global.System.Object, unhandledExceptionArgs As ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
		Write(".UnhandledExceptionEventArgs)\r\n                If Global.System.Diagnostics.Debugger.IsAttached Then\r\n                    Global.System.Diagnostics.Debugger.Break()\r\n                End If\r\n            End Sub\r\n#End If\r\n    End Sub\r\n\r\nEnd Class\r\n\r\nEnd Namespace\r\n");
		return base.GenerationEnvironment.ToString();
	}
}
