using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class CppWinRT_TypeInfoPass1 : CppWinRT_CodeGenerator<TypeInfoDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n#pragma once\r\n\r\n#include <functional>\r\n#include <map>\r\n#include <vector>\r\n#include <unknwn.h>\r\n#include <mutex>\r\n\r\n// Undefine GetCurrentTime macro to prevent\r\n// conflict with Storyboard::GetCurrentTime\r\n#undef GetCurrentTime\r\n\r\n#include <winrt/Windows.Foundation.h>\r\n#include <winrt/Windows.Foundation.Collections.h>\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml"));
		Write(".h\"\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml.Data"));
		Write(".h\"\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml.Markup"));
		Write(".h\"\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml.Interop"));
		Write(".h\"\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Windows.UI.Xaml.Interop"));
		Write(".h\"\r\n#include \"winrt/");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml.XamlTypeInfo"));
		Write(".h\"\r\n\r\nnamespace winrt::");
		Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Colonize(base.ProjectInfo.RootNamespace)));
		Write("::implementation\r\n{\r\n    using IInspectable = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
		Write("::IInspectable;\r\n    using IXamlMember = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember;\r\n    using IXamlType = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType;\r\n\r\n    struct XamlTypeInfoProvider : public std::enable_shared_from_this<XamlTypeInfoProvider>\r\n    {\r\n        IXamlType GetXamlTypeByName(::winrt::hstring const& typeName);\r\n        IXamlType GetXamlTypeByType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName const& t);\r\n        IXamlMember GetMemberByLongName(::winrt::hstring const& longMemberName);\r\n");
		if (!base.ProjectInfo.GenerateProviderCode)
		{
			Write("        void AddOtherProvider(");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider otherProvider);\r\n");
		}
		Write("\r\n    private:\r\n        std::recursive_mutex _xamlTypesCriticalSection;\r\n        std::recursive_mutex _xamlMembersCriticalSection;\r\n        std::map<std::wstring, ::winrt::weak_ref<IXamlType>> _xamlTypes;\r\n        std::map<std::wstring, IXamlMember> _xamlMembers;\r\n        IXamlType CreateXamlType(::winrt::hstring const& typeName);\r\n        IXamlMember CreateXamlMember(::winrt::hstring const& longMemberName);\r\n\r\n        std::vector<");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMetadataProvider> _otherProviders;\r\n        std::vector<");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMetadataProvider> const& OtherProviders();\r\n\r\n        IXamlType CheckOtherMetadataProvidersForName(::winrt::hstring const& typeName);\r\n        IXamlType CheckOtherMetadataProvidersForType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName const& t);\r\n    };\r\n\r\n    struct XamlSystemBaseType : public ::winrt::implements<XamlSystemBaseType, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType>\r\n    {\r\n        explicit XamlSystemBaseType(::winrt::hstring const& name);\r\n\r\n        // IXamlType\r\n        IXamlType BaseType() const;\r\n        IXamlMember ContentProperty() const;\r\n        ::winrt::hstring FullName() const;\r\n        ::winrt::hstring Name() const;\r\n        bool IsArray() const;\r\n        bool IsCollection() const;\r\n        bool IsConstructible() const;\r\n        bool IsDictionary() const;\r\n        bool IsMarkupExtension() const;\r\n        bool IsEnum() const;\r\n        bool IsSystemType() const;\r\n        bool IsBindable() const;\r\n        IXamlType ItemType() const;\r\n        IXamlType KeyType() const;\r\n        IXamlType BoxedType() const;\r\n\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName UnderlyingType() const;\r\n        IInspectable ActivateInstance() const;\r\n        IInspectable CreateFromString(::winrt::hstring const& value) const;\r\n        IXamlMember GetMember(::winrt::hstring const& name) const;\r\n        void AddToVector(IInspectable const& instance, IInspectable const& value) const;\r\n        void AddToMap(IInspectable const& instance, IInspectable const& key, IInspectable const& value) const;\r\n        void RunInitializer() const;\r\n\r\n    private:\r\n        ::winrt::hstring _fullName;\r\n    };\r\n\r\n    struct __declspec(uuid(\"63A5FDC1-874E-4D22-9BC7-A0E3488AD5B2\")) IXamlUserType : ::IUnknown\r\n    {\r\n        virtual bool IsReturnTypeStub() const = 0;\r\n        virtual bool IsLocalType() const = 0;\r\n    };\r\n\r\n");
		string objectToConvert = CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup") + "::IXamlType";
		Write("    struct XamlUserType : public ::winrt::implements<XamlUserType, IXamlUserType, ");
		Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
		Write(">\r\n    {\r\n        explicit XamlUserType(\r\n            std::shared_ptr<XamlTypeInfoProvider> const& provider, \r\n            ::winrt::hstring const& fullName, \r\n            IXamlType baseType);\r\n\r\n        ::winrt::hstring GetRuntimeClassName() const;\r\n\r\n        // IXamlType\r\n        IXamlType BaseType() const;\r\n        IXamlMember ContentProperty() const;\r\n        ::winrt::hstring FullName() const;\r\n        ::winrt::hstring Name() const;\r\n        bool IsArray() const;\r\n        bool IsCollection() const;\r\n        bool IsConstructible() const;\r\n        bool IsDictionary() const;\r\n        bool IsMarkupExtension() const;\r\n        bool IsEnum() const;\r\n        bool IsSystemType() const;\r\n        bool IsBindable() const;\r\n        IXamlType ItemType() const;\r\n        IXamlType KeyType() const;\r\n        IXamlType BoxedType() const;\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName UnderlyingType() const;\r\n        IInspectable ActivateInstance() const;\r\n        IInspectable CreateFromString(::winrt::hstring const& value) const;\r\n        IXamlMember GetMember(::winrt::hstring const& name) const;\r\n        void AddToVector(IInspectable const& instance, IInspectable const& value) const;\r\n        void AddToMap(IInspectable const& instance, IInspectable const& key, IInspectable const& value) const;\r\n        void RunInitializer() const;\r\n\r\n        // Additional Setters\r\n        void IsArray(bool value);\r\n        void IsMarkupExtension(bool value);\r\n        void IsEnum(bool value);\r\n        void IsBindable(bool value);\r\n\r\n        bool IsReturnTypeStub() const;\r\n        void IsReturnTypeStub(bool value);\r\n\r\n        bool IsLocalType() const;\r\n        void IsLocalType(bool value);\r\n\r\n        typedef IInspectable(*ActivatorFn)();\r\n        typedef void(*AddToCollectionFn)(IInspectable const& instance, IInspectable const& item);\r\n        typedef void(*AddToDictionaryFn)(IInspectable const& instance, IInspectable const& key, IInspectable const& item);\r\n        typedef IInspectable (*CreateFromStringFn)(::winrt::hstring const& input);\r\n        typedef IInspectable(*StringConverterFn)(XamlUserType const& userType, ::winrt::hstring const& input);\r\n\r\n        ActivatorFn _activator{};\r\n        AddToCollectionFn _collectionAdd{};\r\n        AddToDictionaryFn _dictionaryAdd{};\r\n        CreateFromStringFn _createFromStringMethod{};\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeKind _kindOfType{};\r\n        StringConverterFn _fromStringConverter{};\r\n\r\n        void ContentPropertyName(::winrt::hstring const& value);\r\n        void ItemTypeName(::winrt::hstring const& value);\r\n        void KeyTypeName(::winrt::hstring const& value);\r\n        void SetBoxedType(IXamlType boxedType);\r\n        void AddMemberName(::winrt::hstring const& shortName);\r\n        void AddEnumValue(::winrt::hstring const& name, IInspectable value);\r\n        uint32_t CreateEnumUIntFromString(::winrt::hstring const& input) const;\r\n\r\n    private:\r\n        std::shared_ptr<XamlTypeInfoProvider> _provider;\r\n        IXamlType _baseType;\r\n        IXamlType _boxedType;\r\n        ::winrt::hstring _contentPropertyName;\r\n        ::winrt::hstring _itemTypeName;\r\n        ::winrt::hstring _keyTypeName;\r\n        ::winrt::hstring _fullName;\r\n        std::map<std::wstring, winrt::hstring> _memberNames;\r\n        std::map<std::wstring, IInspectable> _enumValues;\r\n        bool _isArray{ false };\r\n        bool _isMarkupExtension{ false };\r\n        bool _isEnum{ false };\r\n        bool _isBindable{ false };\r\n        bool _isReturnTypeStub{ false };\r\n        bool _isLocalType{ false };\r\n    };\r\n\r\n    struct XamlMember : public ::winrt::implements<XamlMember, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember>\r\n    {\r\n        explicit XamlMember(\r\n            std::shared_ptr<XamlTypeInfoProvider> const& provider, \r\n            ::winrt::hstring const& name, \r\n            ::winrt::hstring const& typeName);\r\n\r\n        typedef IInspectable(*PropertyGetterFn)(IInspectable const& instance);\r\n        typedef void(*PropertySetterFn)(IInspectable const& instance, IInspectable const& value);\r\n\r\n        PropertyGetterFn _getter{};\r\n        PropertySetterFn _setter{};\r\n\r\n        // IXamlMember\r\n        bool IsAttachable() const;\r\n        bool IsDependencyProperty() const;\r\n        bool IsReadOnly() const;\r\n        ::winrt::hstring Name() const;\r\n        IXamlType TargetType() const;\r\n        IXamlType Type() const;\r\n        IInspectable GetValue(IInspectable const& instance) const;\r\n        void SetValue(IInspectable const& instance, IInspectable const& value);\r\n\r\n        // Additional Setters\r\n        void TargetTypeName(::winrt::hstring const& value);\r\n        void IsAttachable(bool value);\r\n        void IsDependencyProperty(bool value);\r\n        void IsReadOnly(bool value);\r\n\r\n    private:\r\n        bool _isAttachable{ false };\r\n        bool _isDependencyProperty{ false };\r\n        bool _isReadOnly{ false };\r\n        ::winrt::hstring _name;\r\n        ::winrt::hstring _targetTypeName;\r\n        ::winrt::hstring _typeName;\r\n        std::shared_ptr<XamlTypeInfoProvider> _provider;\r\n    };\r\n}\r\n");
		return base.GenerationEnvironment.ToString();
	}
}
