using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class CppWinRT_XamlMetaDataProviderPass1 : CppWinRT_CodeGenerator<TypeInfoDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n#pragma once\r\n\r\n#include <functional>\r\n#include <map>\r\n#include <vector>\r\n#include <unknwn.h>\r\n\r\n// Undefine GetCurrentTime macro to prevent\r\n// conflict with Storyboard::GetCurrentTime\r\n#undef GetCurrentTime\r\n\r\n#include \"XamlTypeInfo.xaml.g.h\"\r\n#include \"XamlMetaDataProvider.g.h\"\r\n\r\n/*\r\n    If the file above was not generated, you may be missing a declaration\r\n    for the XamlMetaDataProvider runtimeclass in your IDL.\r\n\r\n    namespace ");
		Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.RootNamespace));
		Write("\r\n    {\r\n        runtimeclass XamlMetaDataProvider : ");
		Write(base.ToStringHelper.ToStringWithCulture("Microsoft.UI.Xaml.Markup"));
		Write(".IXamlMetadataProvider\r\n        {\r\n            XamlMetaDataProvider();\r\n        };\r\n    }\r\n*/\r\n\r\nnamespace winrt::");
		Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Colonize(base.ProjectInfo.RootNamespace)));
		Write("::implementation\r\n{\r\n    using IXamlMember = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember;\r\n    using IXamlType = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType;\r\n\r\n    struct XamlMetaDataProvider : public ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection(base.ProjectInfo.RootNamespace)));
		Write("::implementation::XamlMetaDataProvider_base<XamlMetaDataProvider>\r\n    {\r\n        IXamlType GetXamlType(");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeName const& type);\r\n        IXamlType GetXamlType(::winrt::hstring const& fullName);\r\n        ::winrt::com_array<");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::XmlnsDefinition> GetXmlnsDefinitions();\r\n");
		if (!base.ProjectInfo.GenerateProviderCode)
		{
			Write("        void AddOtherProvider(");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider otherProvider);\r\n");
		}
		Write("\r\n    private:\r\n        std::shared_ptr<XamlTypeInfoProvider> _provider;\r\n        std::shared_ptr<XamlTypeInfoProvider> Provider();\r\n    };\r\n}\r\n\r\nnamespace winrt::");
		Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Colonize(base.ProjectInfo.RootNamespace)));
		Write("::factory_implementation\r\n{\r\n    struct XamlMetaDataProvider : XamlMetaDataProviderT<XamlMetaDataProvider, implementation::XamlMetaDataProvider>\r\n    {\r\n    };\r\n}\r\n");
		return base.GenerationEnvironment.ToString();
	}
}
