using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using Microsoft.UI.Xaml.Markup.Compiler.Properties;
using Microsoft.UI.Xaml.Markup.Compiler.Utilities;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class CppWinRT_TypeInfoPass2 : CppWinRT_CodeGenerator<TypeInfoDefinition>
{
	private HashSet<TypeGenInfo> staticAssertTypes = new HashSet<TypeGenInfo>();

	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n");
		if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.PrecompiledHeaderFile));
			Write("\"\r\n");
		}
		Write("#include <memory>\r\n#include <unknwn.h>\r\n\r\n// Undefine GetCurrentTime macro to prevent\r\n// conflict with Storyboard::GetCurrentTime\r\n#undef GetCurrentTime\r\n\r\n");
		foreach (string neededCppWinRTProjectionHeaderFile in base.Model.NeededCppWinRTProjectionHeaderFiles)
		{
			Write("#if __has_include(<");
			Write(base.ToStringHelper.ToStringWithCulture(neededCppWinRTProjectionHeaderFile));
			Write(">)\r\n#include <");
			Write(base.ToStringHelper.ToStringWithCulture(neededCppWinRTProjectionHeaderFile));
			Write(">\r\n#endif\r\n");
		}
		Write("\r\n");
		if (base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			Write("#ifdef XAML_TYPE_INFO_INC\r\n#include XAML_TYPE_INFO_INC\r\n#endif\r\n");
		}
		Write("#include \"XamlTypeInfo.xaml.g.h\"\r\n\r\n");
		if (!base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			foreach (string allLocalXamlHeaderFile in base.Model.AllLocalXamlHeaderFiles)
			{
				Write("#include \"");
				Write(base.ToStringHelper.ToStringWithCulture(allLocalXamlHeaderFile));
				Write("\"\r\n");
			}
		}
		Write("#include \"XamlBindingInfo.xaml.g.hpp\"\r\n");
		if (!base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			foreach (string allLocalHppGeneratedFile in base.Model.AllLocalHppGeneratedFiles)
			{
				Write("#include \"");
				Write(base.ToStringHelper.ToStringWithCulture(allLocalHppGeneratedFile.Replace(".g.hpp", ".xaml.g.hpp")));
				Write("\"\r\n");
			}
		}
		Write("\r\nnamespace winrt::");
		Write(base.ToStringHelper.ToStringWithCulture(NativeCodeGenerator<TypeInfoDefinition>.Colonize(base.ProjectInfo.RootNamespace)));
		Write("::implementation\r\n{\r\nusing IXamlMember = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMember;\r\nusing IXamlType = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlType;\r\nusing TypeKind = ");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
		Write("::TypeKind;\r\n");
		if (base.Model.TypeInfos.Any())
		{
			if (base.ProjectInfo.GenerateCppWinRTStaticAsserts)
			{
				Write("\r\n    namespace XamlTypeInfo_staticasserts\r\n    {\r\n        template<typename, typename = void>\r\n        constexpr bool is_type_complete_v = false;\r\n\r\n        template<typename T>\r\n        constexpr bool is_type_complete_v<T, std::void_t<decltype(sizeof(T))>> = true;\r\n\r\n");
				foreach (TypeGenInfo typeInfo in base.Model.TypeInfos)
				{
					Output_StaticAssertTypeIsComplete(typeInfo, Indent.TwoTabs);
				}
				Write("\r\n    }\r\n");
			}
			Write("\r\n");
			if (base.ProjectInfo.GenerateIncrementalTypeInfo)
			{
				foreach (TypeGenInfo item in base.Model.TypeInfos.OrderBy((TypeGenInfo t) => t.StandardName))
				{
					IncludeTemplate<CppWinRT_MetadataDelegates>(item, new object[1] { base.ProjectInfo.ClassToHeaderFileMap.ContainsKey(item.StandardName) });
				}
			}
			else
			{
				IncludeTemplate<CppWinRT_TemplatedMetadataDelegates>(base.Model, Array.Empty<object>());
			}
			Write("\r\nenum TypeInfo_Flags\r\n{\r\n    TypeInfo_Flags_None                 = 0x00,\r\n    TypeInfo_Flags_IsLocalType          = 0x01,\r\n    TypeInfo_Flags_IsSystemType         = 0x02,\r\n    TypeInfo_Flags_IsReturnTypeStub     = 0x04,\r\n    TypeInfo_Flags_IsBindable           = 0x08,\r\n    TypeInfo_Flags_IsMarkupExtension    = 0x10, \r\n};\r\n\r\nstruct TypeInfo\r\n{\r\n    const wchar_t* typeName{nullptr};\r\n    const wchar_t* contentPropertyName{nullptr};\r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable (*activator)();\r\n    void (*collectionAdd)(");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable const&, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable const&);\r\n    void (*dictionaryAdd)(");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable const&, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable const&, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable const&);\r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
			Write("::IInspectable (*fromStringConverter)(XamlUserType const&, ::winrt::hstring const& );\r\n    int     baseTypeIndex;\r\n    int     firstMemberIndex;\r\n    int     firstEnumValueIndex;\r\n    int     createFromStringIndex;\r\n    TypeKind kindOfType;\r\n    unsigned int flags;\r\n    int boxedTypeIndex;\r\n};\r\n\r\n");
			if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
			{
				Write("#pragma warning( push )\r\n#pragma warning( disable : 4973 )\r\n");
			}
			if (base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod).Any())
			{
				Write("\r\nXamlUserType::CreateFromStringFn CreateFromStringMethods[] =\r\n{\r\n");
				foreach (TypeGenInfo item2 in base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod))
				{
					Write("    [](::winrt::hstring const& value) -> ::winrt::Windows::Foundation::IInspectable { return ::winrt::box_value(");
					Write(base.ToStringHelper.ToStringWithCulture(item2.CreateFromStringMethod.ResolvedName.CppWinRTName()));
					Write("(value)); },\r\n");
				}
				Write("};\r\n");
			}
			Write("\r\nconst TypeInfo TypeInfos[] = \r\n{\r\n");
			int num = 0;
			int startIndex = 0;
			int startIndex2 = 0;
			int num2 = 0;
			foreach (TypeGenInfo typeInfo2 in base.Model.TypeInfos)
			{
				string objectToConvert = (typeInfo2.IsLocalType ? "TypeInfo_Flags_IsLocalType | " : "");
				string objectToConvert2 = (typeInfo2.IsSystemType ? "TypeInfo_Flags_IsSystemType | " : "");
				string objectToConvert3 = (typeInfo2.IsReturnTypeStub ? "TypeInfo_Flags_IsReturnTypeStub | " : "");
				string objectToConvert4 = (typeInfo2.IsBindable ? "TypeInfo_Flags_IsBindable | " : "");
				string objectToConvert5 = (typeInfo2.IsMarkupExtension ? "TypeInfo_Flags_IsMarkupExtension | " : "");
				string objectToConvert6 = ((typeInfo2.BaseTypeStandardName.Length > 0) ? (base.Model.TypeInfoIndexes[typeInfo2.BaseTypeStandardName] + ", // " + typeInfo2.BaseTypeStandardName) : "-1,");
				string objectToConvert7 = ((typeInfo2.BoxedTypeStandardName.Length > 0) ? (base.Model.TypeInfoIndexes[typeInfo2.BoxedTypeStandardName] + ", // " + typeInfo2.BoxedTypeStandardName) : "-1,");
				string objectToConvert8 = string.Format("TypeKind::{0}", (typeInfo2.IsLocalType && !base.ProjectInfo.IsLibrary) ? "Custom" : "Metadata");
				string objectToConvert9 = (typeInfo2.HasActivator ? ("&" + typeInfo2.ActivatorName.CppWinRTName()) : "nullptr");
				string objectToConvert10 = (typeInfo2.IsCollection ? ("&" + typeInfo2.CollectionAddName.CppWinRTName()) : "nullptr");
				string objectToConvert11 = (typeInfo2.IsDictionary ? ("&" + typeInfo2.DictionaryAddName.CppWinRTName()) : "nullptr");
				string objectToConvert12 = (typeInfo2.HasEnumValues ? ("&" + typeInfo2.FromStringConverterName.CppWinRTName()) : "nullptr");
				string objectToConvert13 = "-1";
				if (typeInfo2.HasCreateFromStringMethod)
				{
					objectToConvert13 = num2.ToString();
					num2++;
				}
				if (typeInfo2.HasMembers)
				{
					base.Model.TrackTypeMembers(typeInfo2, out startIndex2);
				}
				if (typeInfo2.HasEnumValues)
				{
					base.Model.TrackTypeEnumValues(typeInfo2, out startIndex);
				}
				Write("    // ");
				Write(base.ToStringHelper.ToStringWithCulture($"{num++,3}"));
				Write("\r\n    L\"");
				Write(base.ToStringHelper.ToStringWithCulture(typeInfo2.StandardName));
				Write("\", L\"");
				Write(base.ToStringHelper.ToStringWithCulture(typeInfo2.ContentPropertyName));
				Write("\",\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert9));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert10));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert11));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert12));
				Write(",\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert6));
				Write("\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(startIndex2));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(startIndex));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert13));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert8));
				Write(",\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert2));
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert3));
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert4));
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert5));
				Write("TypeInfo_Flags_None,\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(objectToConvert7));
				Write("\r\n");
				startIndex += typeInfo2.EnumValues.Count();
				startIndex2 += typeInfo2.Members.Count();
			}
			Write("    //  Last type here is for padding\r\n    L\"\", L\"\",\r\n    nullptr, nullptr, nullptr, nullptr,\r\n    -1, \r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(startIndex2));
			Write(", ");
			Write(base.ToStringHelper.ToStringWithCulture(startIndex));
			Write(", -1, TypeKind::Custom,\r\n    TypeInfo_Flags_None,\r\n};\r\n");
			if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
			{
				Write("#pragma warning( pop )\r\n");
			}
			Write("\r\n");
			num = 0;
			Write("constexpr uint32_t TypeInfoLookup[] = { \r\n");
			foreach (uint item3 in base.Model.TypeInfoLookup)
			{
				Write("    ");
				Write(base.ToStringHelper.ToStringWithCulture($"{item3,3},   // {num++,3}"));
				Write("\r\n");
			}
			Write("};\r\n");
			if (base.Model.EnumValues.Count() > 0)
			{
				Write("\r\nstruct EnumValueInfo\r\n{\r\n    const wchar_t* name{nullptr};\r\n    int eValue;\r\n};\r\n\r\nconst EnumValueInfo EnumValues[] =\r\n{ \r\n");
				foreach (EnumGenInfo enumValue in base.Model.EnumValues)
				{
					Write("    L\"");
					Write(base.ToStringHelper.ToStringWithCulture(enumValue.ValueName));
					Write("\", static_cast<int>(");
					Write(base.ToStringHelper.ToStringWithCulture(enumValue.TypeInfo.FullName));
					Write("::");
					Write(base.ToStringHelper.ToStringWithCulture(enumValue.ValueName));
					Write("),\r\n");
				}
				Write("};\r\n");
			}
			if (base.Model.MemberInfos.Count() > 0)
			{
				Write("\r\nstruct MemberInfo \r\n{\r\n    const wchar_t* shortName{nullptr};\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
				Write("::IInspectable (*getter)(");
				Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
				Write("::IInspectable const&);\r\n    void (*setter)(");
				Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
				Write("::IInspectable const&, ");
				Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Windows.Foundation")));
				Write("::IInspectable const&);\r\n    int typeIndex;\r\n    int targetTypeIndex;\r\n    bool isReadOnly;\r\n    bool isDependencyProperty;\r\n    bool isAttachable;\r\n};\r\n\r\n");
				if (base.Model.MemberInfos.Where((MemberGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("#pragma warning( push )\r\n#pragma warning( disable : 4973 )\r\n");
				}
				Write("const MemberInfo MemberInfos[] = \r\n{\r\n");
				num = 0;
				foreach (MemberGenInfo memberInfo in base.Model.MemberInfos)
				{
					string objectToConvert14 = ((memberInfo.HasPublicGetter && !memberInfo.HasPublicSetter) ? "true, " : "false,");
					string objectToConvert15 = (memberInfo.IsDependencyProperty ? "true, " : "false,");
					string objectToConvert16 = (memberInfo.IsAttachable ? "true, " : "false,");
					string objectToConvert17 = ((memberInfo.TargetType != null) ? (base.Model.TypeInfoIndexes[memberInfo.TargetType.StandardName] + ", // " + memberInfo.TargetType.StandardName) : "-1,");
					Write("    // ");
					Write(base.ToStringHelper.ToStringWithCulture($"{num++,3}"));
					Write(" - ");
					Write(base.ToStringHelper.ToStringWithCulture(memberInfo.DeclaringType.StandardName));
					Write(".");
					Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Name));
					Write("\r\n    L\"");
					Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Name));
					Write("\",\r\n");
					if (memberInfo.HasGetAttachableMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetAttachableMemberName));
						Write(",\r\n");
					}
					else if (memberInfo.HasGetValueTypeMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetValueTypeMemberName));
						Write(",\r\n");
					}
					else if (memberInfo.HasGetReferenceTypeMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetReferenceTypeMemberName));
						Write(",\r\n");
					}
					else
					{
						Write("    nullptr,\r\n");
					}
					if (memberInfo.HasSetAttachableMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetAttachableMemberName));
						Write(",\r\n");
					}
					else if (memberInfo.HasSetEnumMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetEnumMemberName));
						Write(",\r\n");
					}
					else if (memberInfo.HasSetValueTypeMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetValueTypeMemberName));
						Write(",\r\n");
					}
					else if (memberInfo.HasSetReferenceTypeMember)
					{
						Write("    &");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetReferenceTypeMemberName));
						Write(",\r\n");
					}
					else
					{
						Write("    nullptr,\r\n");
					}
					Write("    ");
					Write(base.ToStringHelper.ToStringWithCulture(base.Model.TypeInfoIndexes[memberInfo.Type.StandardName]));
					Write(", // ");
					Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Type.StandardName));
					Write("\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert17));
					Write("\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert14));
					Write(" ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert15));
					Write(" ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert16));
					Write("\r\n");
				}
				Write("};\r\n");
				if (base.Model.MemberInfos.Where((MemberGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("#pragma warning( pop )\r\n");
				}
				Write("\r\nconst wchar_t* GetShortName(const wchar_t* longName)\r\n{\r\n    const auto separator = wcsrchr(longName, '.');\r\n    return separator ? separator + 1: longName;\r\n}\r\n");
			}
			Write("\r\nconst TypeInfo* GetTypeInfo(::winrt::hstring const& typeName)\r\n{\r\n    size_t typeNameLength = typeName.size();\r\n    if (typeNameLength < _countof(TypeInfoLookup) - 1)\r\n    {\r\n        const auto begin = TypeInfos + TypeInfoLookup[typeNameLength];\r\n        const auto end = TypeInfos + TypeInfoLookup[typeNameLength + 1];\r\n        auto pos = std::find_if(begin, end, [&typeName](TypeInfo const& elem)\r\n        {\r\n            return wcscmp(typeName.data(), elem.typeName) == 0;\r\n        });\r\n        if (pos != end)\r\n        {\r\n            return pos;\r\n        }\r\n    }\r\n    return nullptr;\r\n}\r\n");
			if (base.Model.MemberInfos.Count() > 0)
			{
				Write("\r\nconst MemberInfo* GetMemberInfo(::winrt::hstring const& longMemberName)\r\n{\r\n    const auto dotPosition = std::find(longMemberName.crbegin(), longMemberName.crend(), L'.').base();\r\n    if (dotPosition != longMemberName.end())\r\n    {\r\n        const auto sizeBeforeDot = static_cast<::winrt::hstring::size_type>(dotPosition - longMemberName.begin()) - 1;\r\n        const TypeInfo* pTypeInfo = GetTypeInfo(::winrt::hstring{longMemberName.data(), sizeBeforeDot});\r\n        if (pTypeInfo)\r\n        {\r\n            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;\r\n            const auto shortMemberName = GetShortName(longMemberName.data());\r\n            const auto begin = MemberInfos + pTypeInfo->firstMemberIndex;\r\n            const auto end = MemberInfos + pNextTypeInfo->firstMemberIndex;\r\n            auto info = std::find_if(begin, end,\r\n                [shortMemberName](const MemberInfo& elem)\r\n            {\r\n                return wcscmp(shortMemberName, elem.shortName) == 0;\r\n            });\r\n            if (info != end)\r\n            {\r\n                return info;\r\n            }\r\n        }\r\n    }\r\n    return nullptr;\r\n}\r\n");
			}
		}
		Write("\r\nstd::vector<");
		Write(base.ToStringHelper.ToStringWithCulture(CppWinRT_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IXamlMetadataProvider> const& XamlTypeInfoProvider::OtherProviders()\r\n{\r\n");
		if (base.ProjectInfo.GenerateProviderCode && base.SchemaInfo.OtherMetadataProviders.Any())
		{
			Write("    std::lock_guard<std::recursive_mutex> lock(_xamlTypesCriticalSection);\r\n    if (_otherProviders.empty())\r\n    {\r\n");
			foreach (TypeForCodeGen otherMetadataProvider in base.SchemaInfo.OtherMetadataProviders)
			{
				Write("        _otherProviders.push_back(");
				Write(base.ToStringHelper.ToStringWithCulture(otherMetadataProvider.FullName));
				Write("());\r\n");
			}
			Write("    }\r\n");
		}
		Write("    return _otherProviders;\r\n}\r\n\r\n");
		if (!base.Model.TypeInfos.Any())
		{
			Write("IXamlType XamlTypeInfoProvider::CreateXamlType(::winrt::hstring const& )\r\n{\r\n    // No local types\r\n    return nullptr;\r\n}\r\n");
		}
		else
		{
			Write("IXamlType XamlTypeInfoProvider::CreateXamlType(::winrt::hstring const& typeName)\r\n{\r\n    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);\r\n    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;\r\n    if (!pTypeInfo || !pNextTypeInfo)\r\n    {\r\n        return nullptr;\r\n    }\r\n    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)\r\n    {\r\n        return ::winrt::make<XamlSystemBaseType>(typeName);\r\n    }\r\n    else\r\n    {\r\n        ::winrt::hstring baseName { pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L\"\"};\r\n        ::winrt::hstring boxedName { pTypeInfo->boxedTypeIndex >= 0 ? TypeInfos[pTypeInfo->boxedTypeIndex].typeName : L\"\"};\r\n        auto userType = ::winrt::make_self<XamlUserType>(shared_from_this(), pTypeInfo->typeName, GetXamlTypeByName(baseName));\r\n        userType->_kindOfType = pTypeInfo->kindOfType;\r\n        userType->_activator = pTypeInfo->activator;\r\n        userType->_collectionAdd = pTypeInfo->collectionAdd;\r\n        userType->_dictionaryAdd = pTypeInfo->dictionaryAdd;\r\n        userType->_fromStringConverter = pTypeInfo->fromStringConverter;\r\n        userType->ContentPropertyName(pTypeInfo->contentPropertyName);\r\n        userType->IsLocalType(pTypeInfo->flags & TypeInfo_Flags_IsLocalType);\r\n        userType->IsReturnTypeStub(pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub);\r\n        userType->IsBindable(pTypeInfo->flags & TypeInfo_Flags_IsBindable);\r\n        userType->IsMarkupExtension(pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension);\r\n        userType->_createFromStringMethod = nullptr;\r\n");
			if (base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod).Any())
			{
				Write("        if (pTypeInfo->createFromStringIndex != -1)\r\n        {\r\n            userType->_createFromStringMethod = CreateFromStringMethods[pTypeInfo->createFromStringIndex];\r\n        }\r\n");
			}
			Write("        userType->SetBoxedType(GetXamlTypeByName(boxedName));\r\n");
			if (base.Model.MemberInfos.Any())
			{
				Write("        for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; ++i)\r\n        {\r\n            userType->AddMemberName(MemberInfos[i].shortName);\r\n        }\r\n");
			}
			if (base.Model.EnumValues.Any())
			{
				Write("        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; ++i)\r\n        {\r\n            userType->AddEnumValue(EnumValues[i].name, winrt::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));\r\n        }\r\n");
			}
			Write("        return userType.as<IXamlType>();\r\n    }\r\n}\r\n");
		}
		Write("\r\n");
		if (!base.Model.MemberInfos.Any())
		{
			Write("IXamlMember XamlTypeInfoProvider::CreateXamlMember(::winrt::hstring const& )\r\n{\r\n    // No local properties\r\n    return nullptr;\r\n}\r\n");
		}
		else
		{
			Write("IXamlMember XamlTypeInfoProvider::CreateXamlMember(::winrt::hstring const& longMemberName)\r\n{\r\n    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);\r\n    if (!pMemberInfo)\r\n    {\r\n        return nullptr;\r\n    }\r\n    auto xamlMember = ::winrt::make_self<XamlMember>(shared_from_this(),\r\n        pMemberInfo->shortName, TypeInfos[pMemberInfo->typeIndex].typeName);\r\n    xamlMember->_getter = pMemberInfo->getter;\r\n    xamlMember->_setter = pMemberInfo->setter;\r\n    xamlMember->TargetTypeName(pMemberInfo->targetTypeIndex >= 0 ? TypeInfos[pMemberInfo->targetTypeIndex].typeName : L\"\");\r\n    xamlMember->IsReadOnly(pMemberInfo->isReadOnly);\r\n    xamlMember->IsDependencyProperty(pMemberInfo->isDependencyProperty);\r\n    xamlMember->IsAttachable(pMemberInfo->isAttachable);\r\n\r\n    return xamlMember.as<IXamlMember>();\r\n}\r\n");
		}
		Write("} // namespace\r\n\r\n");
		return base.GenerationEnvironment.ToString();
	}

	private void Output_StaticAssertTypeIsComplete(TypeGenInfo typeInfo, Indent indent = Indent.None)
	{
		if ((typeInfo.HasActivator || typeInfo.IsCollection || typeInfo.IsDictionary || typeInfo.HasEnumValues) && !staticAssertTypes.Contains(typeInfo))
		{
			staticAssertTypes.Add(typeInfo);
			PushIndent(indent);
			if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
			{
				Write("static_assert( is_type_complete_v<");
				Write(base.ToStringHelper.ToStringWithCulture(typeInfo.FullName.CppWinRTName()));
				Write(">, \"");
				Write(base.ToStringHelper.ToStringWithCulture(ResourceUtilities.FormatString(XamlCompilerResources.XamlCompiler_CodeGenStaticAssert_IncompleteType, typeInfo.FullName.CppWinRTName(), base.ProjectInfo.PrecompiledHeaderFile)));
				Write("\" );\r\n");
			}
			else
			{
				Write("static_assert( is_type_complete_v<");
				Write(base.ToStringHelper.ToStringWithCulture(typeInfo.FullName.CppWinRTName()));
				Write(">, \"");
				Write(base.ToStringHelper.ToStringWithCulture(ResourceUtilities.FormatString(XamlCompilerResources.XamlCompiler_CodeGenStaticAssert_IncompleteType_NoPch, typeInfo.FullName.CppWinRTName())));
				Write("\" );\r\n");
			}
			PopIndent();
		}
	}
}
