using System;
using System.CodeDom.Compiler;
using System.Linq;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class MoComCppTypeInfoPass2 : CppCX_CodeGenerator<TypeInfoDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n");
		if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.PrecompiledHeaderFile));
			Write("\"\r\n");
		}
		if (base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			Write("#ifdef XAML_TYPE_INFO_INC\r\n#include XAML_TYPE_INFO_INC\r\n#endif\r\n");
		}
		Write("#include \"XamlTypeInfo.g.h\"\r\n\r\n");
		if (!base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			foreach (string allLocalXamlHeaderFile in base.Model.AllLocalXamlHeaderFiles)
			{
				Write("#include \"");
				Write(base.ToStringHelper.ToStringWithCulture(allLocalXamlHeaderFile));
				Write("\"\r\n");
			}
		}
		Write("#include \"XamlBindingInfo.g.hpp\"\r\n");
		if (!base.ProjectInfo.GenerateIncrementalTypeInfo)
		{
			foreach (string allLocalHppGeneratedFile in base.Model.AllLocalHppGeneratedFiles)
			{
				Write("#include \"");
				Write(base.ToStringHelper.ToStringWithCulture(allLocalHppGeneratedFile));
				Write("\"\r\n");
			}
		}
		if (base.Model.TypeInfos.Count() > 0)
		{
			Write("\r\n");
			if (base.ProjectInfo.GenerateIncrementalTypeInfo)
			{
				foreach (TypeGenInfo item in base.Model.TypeInfos.OrderBy((TypeGenInfo t) => t.StandardName))
				{
					IncludeTemplate<CXMetadataDelegates>(item, new object[1] { base.ProjectInfo.ClassToHeaderFileMap.ContainsKey(item.StandardName) });
				}
			}
			else
			{
				IncludeTemplate<CXTemplatedMetadataDelegates>(base.Model, Array.Empty<object>());
			}
			if (!base.ProjectInfo.EnableTypeInfoReflection)
			{
				Write("\r\nenum TypeInfo_Flags\r\n{\r\n    TypeInfo_Flags_None                 = 0x00,\r\n    TypeInfo_Flags_IsLocalType          = 0x01,\r\n    TypeInfo_Flags_IsSystemType         = 0x02,\r\n    TypeInfo_Flags_IsReturnTypeStub     = 0x04,\r\n    TypeInfo_Flags_IsBindable           = 0x08,\r\n    TypeInfo_Flags_IsMarkupExtension    = 0x10, \r\n};\r\n\r\nstruct TypeInfo\r\n{\r\n    PCWSTR  typeName;\r\n    PCWSTR contentPropertyName;\r\n    ::Platform::Object^ (*activator)();\r\n    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);\r\n    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);\r\n    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);\r\n    int     baseTypeIndex;\r\n    int     firstMemberIndex;\r\n    int     firstEnumValueIndex;\r\n    int     createFromStringIndex;\r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
				Write("::TypeKind kindofType;\r\n    unsigned int flags;\r\n    int boxedTypeIndex;\r\n};\r\n");
				if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("\r\n#pragma warning( push )\r\n#pragma warning( disable : 4973 )\r\n");
				}
				if (base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod).Any() && !base.ProjectInfo.EnableTypeInfoReflection)
				{
					Write("\r\n::XamlTypeInfo::InfoProvider::XamlUserType::CreateFromStringFn CreateFromStringMethods[] =\r\n{\r\n");
					foreach (TypeGenInfo item2 in base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod))
					{
						Write("    [](::Platform::String^ value) -> ::Platform::Object^ { return ");
						Write(base.ToStringHelper.ToStringWithCulture(item2.CreateFromStringMethod.ResolvedName.CppCXName()));
						Write("(value); },\r\n");
					}
					Write("};\r\n");
				}
				Write("\r\nconst TypeInfo TypeInfos[] = \r\n{\r\n");
				int num = 0;
				int startIndex = 0;
				int startIndex2 = 0;
				int num2 = 0;
				foreach (TypeGenInfo typeInfo in base.Model.TypeInfos)
				{
					string objectToConvert = (typeInfo.IsLocalType ? "TypeInfo_Flags_IsLocalType | " : "");
					string objectToConvert2 = (typeInfo.IsSystemType ? "TypeInfo_Flags_IsSystemType | " : "");
					string objectToConvert3 = (typeInfo.IsReturnTypeStub ? "TypeInfo_Flags_IsReturnTypeStub | " : "");
					string objectToConvert4 = (typeInfo.IsBindable ? "TypeInfo_Flags_IsBindable | " : "");
					string objectToConvert5 = (typeInfo.IsMarkupExtension ? "TypeInfo_Flags_IsMarkupExtension | " : "");
					string objectToConvert6 = ((typeInfo.BaseTypeStandardName.Length > 0) ? (base.Model.TypeInfoIndexes[typeInfo.BaseTypeStandardName] + ", // " + typeInfo.BaseTypeStandardName) : "-1,");
					string objectToConvert7 = ((typeInfo.BoxedTypeStandardName.Length > 0) ? (base.Model.TypeInfoIndexes[typeInfo.BoxedTypeStandardName] + ", // " + typeInfo.BoxedTypeStandardName) : "-1,");
					string objectToConvert8 = string.Format("{0}::TypeKind::{1}", CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop"), (typeInfo.IsLocalType && !base.ProjectInfo.IsLibrary) ? "Custom" : "Metadata");
					string objectToConvert9 = (typeInfo.HasActivator ? ("&" + typeInfo.ActivatorName.CppCXName()) : "nullptr");
					string objectToConvert10 = (typeInfo.IsCollection ? ("&" + typeInfo.CollectionAddName.CppCXName()) : "nullptr");
					string objectToConvert11 = (typeInfo.IsDictionary ? ("&" + typeInfo.DictionaryAddName.CppCXName()) : "nullptr");
					string objectToConvert12 = (typeInfo.HasEnumValues ? ("&" + typeInfo.FromStringConverterName.CppCXName()) : "nullptr");
					string objectToConvert13 = "-1";
					if (typeInfo.HasCreateFromStringMethod)
					{
						objectToConvert13 = num2.ToString();
						num2++;
					}
					if (typeInfo.HasMembers)
					{
						base.Model.TrackTypeMembers(typeInfo, out startIndex2);
					}
					if (typeInfo.HasEnumValues)
					{
						base.Model.TrackTypeEnumValues(typeInfo, out startIndex);
					}
					Write("    // ");
					Write(base.ToStringHelper.ToStringWithCulture($"{num++,3}"));
					Write("\r\n    L\"");
					Write(base.ToStringHelper.ToStringWithCulture(typeInfo.StandardName));
					Write("\", L\"");
					Write(base.ToStringHelper.ToStringWithCulture(typeInfo.ContentPropertyName));
					Write("\",\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert9));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert10));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert11));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert12));
					Write(",\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert6));
					Write("\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(startIndex2));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(startIndex));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert13));
					Write(", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert8));
					Write(",\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert2));
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert3));
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert4));
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert5));
					Write("TypeInfo_Flags_None,\r\n    ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert7));
					Write("\r\n");
					startIndex += typeInfo.EnumValues.Count();
					startIndex2 += typeInfo.Members.Count();
				}
				Write("    //  Last type here is for padding\r\n    L\"\", L\"\",\r\n    nullptr, nullptr, nullptr, nullptr,\r\n    -1, \r\n    ");
				Write(base.ToStringHelper.ToStringWithCulture(startIndex2));
				Write(", ");
				Write(base.ToStringHelper.ToStringWithCulture(startIndex));
				Write(", -1, ");
				Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Windows.UI.Xaml.Interop")));
				Write("::TypeKind::Custom,\r\n    TypeInfo_Flags_None,\r\n};\r\n");
				if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("#pragma warning( pop )\r\n");
				}
				Write("\r\n");
				num = 0;
				Write("const UINT TypeInfoLookup[] = { \r\n");
				foreach (uint item3 in base.Model.TypeInfoLookup)
				{
					Write("    ");
					Write(base.ToStringHelper.ToStringWithCulture($"{item3,3},   // {num++,3}"));
					Write("\r\n");
				}
				Write("};\r\n\r\n");
				Output_GetTypeInfo();
				if (base.Model.EnumValues.Count() > 0)
				{
					Write("\r\nstruct EnumValueInfo\r\n{\r\n    PCWSTR name;\r\n    int eValue;\r\n};\r\n\r\nconst EnumValueInfo EnumValues[] =\r\n{ \r\n");
					foreach (EnumGenInfo enumValue in base.Model.EnumValues)
					{
						Write("    L\"");
						Write(base.ToStringHelper.ToStringWithCulture(enumValue.ValueName));
						Write("\", (int) ");
						Write(base.ToStringHelper.ToStringWithCulture(enumValue.TypeInfo.FullName));
						Write("::");
						Write(base.ToStringHelper.ToStringWithCulture(enumValue.ValueName));
						Write(",\r\n");
					}
					Write("};\r\n");
				}
				if (base.Model.MemberInfos.Count() > 0)
				{
					Write("\r\nstruct MemberInfo \r\n{\r\n    PCWSTR shortName;\r\n    ::Platform::Object^ (*getter)(::Platform::Object^);\r\n    void (*setter)(::Platform::Object^, ::Platform::Object^);\r\n    int typeIndex;\r\n    int targetTypeIndex;\r\n    bool isReadOnly;\r\n    bool isDependencyProperty;\r\n    bool isAttachable;\r\n};\r\n\r\n");
					if (base.Model.MemberInfos.Where((MemberGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
					{
						Write("#pragma warning( push )\r\n#pragma warning( disable : 4973 )\r\n");
					}
					Write("const MemberInfo MemberInfos[] = \r\n{\r\n");
					num = 0;
					foreach (MemberGenInfo memberInfo in base.Model.MemberInfos)
					{
						string objectToConvert14 = ((memberInfo.HasPublicGetter && !memberInfo.HasPublicSetter) ? "true, " : "false,");
						string objectToConvert15 = (memberInfo.IsDependencyProperty ? "true, " : "false,");
						string objectToConvert16 = (memberInfo.IsAttachable ? "true, " : "false,");
						string objectToConvert17 = ((memberInfo.TargetType != null) ? (base.Model.TypeInfoIndexes[memberInfo.TargetType.StandardName] + ", // " + memberInfo.TargetType.StandardName) : "-1,");
						Write("    // ");
						Write(base.ToStringHelper.ToStringWithCulture($"{num++,3}"));
						Write(" - ");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.DeclaringType.StandardName));
						Write(".");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Name));
						Write("\r\n    L\"");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Name));
						Write("\",\r\n");
						if (memberInfo.HasGetAttachableMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetAttachableMemberName));
							Write(",\r\n");
						}
						else if (memberInfo.HasGetValueTypeMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetValueTypeMemberName));
							Write(",\r\n");
						}
						else if (memberInfo.HasGetReferenceTypeMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.GetReferenceTypeMemberName));
							Write(",\r\n");
						}
						else
						{
							Write("    nullptr,\r\n");
						}
						if (memberInfo.HasSetAttachableMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetAttachableMemberName));
							Write(",\r\n");
						}
						else if (memberInfo.HasSetEnumMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetEnumMemberName));
							Write(",\r\n");
						}
						else if (memberInfo.HasSetValueTypeMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetValueTypeMemberName));
							Write(",\r\n");
						}
						else if (memberInfo.HasSetReferenceTypeMember)
						{
							Write("    &");
							Write(base.ToStringHelper.ToStringWithCulture(memberInfo.SetReferenceTypeMemberName));
							Write(",\r\n");
						}
						else
						{
							Write("    nullptr,\r\n");
						}
						Write("    ");
						Write(base.ToStringHelper.ToStringWithCulture(base.Model.TypeInfoIndexes[memberInfo.Type.StandardName]));
						Write(", // ");
						Write(base.ToStringHelper.ToStringWithCulture(memberInfo.Type.StandardName));
						Write("\r\n    ");
						Write(base.ToStringHelper.ToStringWithCulture(objectToConvert17));
						Write("\r\n    ");
						Write(base.ToStringHelper.ToStringWithCulture(objectToConvert14));
						Write(" ");
						Write(base.ToStringHelper.ToStringWithCulture(objectToConvert15));
						Write(" ");
						Write(base.ToStringHelper.ToStringWithCulture(objectToConvert16));
						Write("\r\n");
					}
					Write("};\r\n");
					if (base.Model.MemberInfos.Where((MemberGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
					{
						Write("#pragma warning( pop )\r\n");
					}
					Write("\r\nPCWSTR GetShortName(PCWSTR longName)\r\n{\r\n    PCWSTR separator = wcsrchr(longName, '.');\r\n    return separator != nullptr ? separator + 1: longName;\r\n}\r\n\r\n");
				}
				if (base.Model.MemberInfos.Count() > 0)
				{
					Write("\r\nconst MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)\r\n{\r\n    auto lastDotIndex = longMemberName->Length();\r\n    while (true)\r\n    {\r\n        if (longMemberName->Data()[lastDotIndex] == '.')\r\n        {\r\n            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));\r\n            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;\r\n            if (pTypeInfo)\r\n            {\r\n                PCWSTR shortMemberName = GetShortName(longMemberName->Data());\r\n                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)\r\n                {\r\n                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)\r\n                    {\r\n                        return &MemberInfos[i];\r\n                    }\r\n                }\r\n            }\r\n            break;\r\n        }\r\n        if (lastDotIndex == 0)\r\n        {\r\n            break;\r\n        }\r\n        lastDotIndex--;\r\n    }\r\n    return nullptr;\r\n}\r\n");
				}
			}
			else
			{
				Write("\r\nstruct TypeInfo\r\n{\r\n    PCWSTR  typeName;\r\n    ::Platform::Object^ (*activator)();\r\n};\r\n");
				if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("\r\n#pragma warning( push )\r\n#pragma warning( disable : 4973 )\r\n");
				}
				if (base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod).Any())
				{
					Write("\r\n::XamlTypeInfo::InfoProvider::XamlUserType::CreateFromStringFn CreateFromStringMethods[] =\r\n{\r\n");
					foreach (TypeGenInfo item4 in base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod))
					{
						Write("    [](::Platform::String^ value) -> ::Platform::Object^ { return ");
						Write(base.ToStringHelper.ToStringWithCulture(item4.CreateFromStringMethod.ResolvedName.CppCXName()));
						Write("(value); },\r\n");
					}
					Write("};\r\n");
				}
				Write("\r\nconst TypeInfo TypeInfos[] = \r\n{\r\n");
				int num3 = 0;
				foreach (TypeGenInfo typeInfo2 in base.Model.TypeInfos)
				{
					string objectToConvert18 = (typeInfo2.HasActivator ? ("&" + typeInfo2.ActivatorName.CppCXName()) : "nullptr");
					Write("    // ");
					Write(base.ToStringHelper.ToStringWithCulture($"{num3++,3}"));
					Write("\r\n    L\"");
					Write(base.ToStringHelper.ToStringWithCulture(typeInfo2.StandardName));
					Write("\", ");
					Write(base.ToStringHelper.ToStringWithCulture(objectToConvert18));
					Write(",\r\n");
				}
				Write("    //  Last type here is for padding\r\n    L\"\", nullptr\r\n};\r\n");
				if (base.Model.TypeInfos.Where((TypeGenInfo x) => x.IsDeprecated).FirstOrDefault() != null)
				{
					Write("#pragma warning( pop )\r\n");
				}
				Write("\r\n");
				num3 = 0;
				Write("const UINT TypeInfoLookup[] = { \r\n");
				foreach (uint item5 in base.Model.TypeInfoLookup)
				{
					Write("    ");
					Write(base.ToStringHelper.ToStringWithCulture($"{item5,3},   // {num3++,3}"));
					Write("\r\n");
				}
				Write("};\r\n");
				Output_GetTypeInfo();
			}
		}
		if (base.ProjectInfo.GenerateOtherProvidersForCX || !base.ProjectInfo.GenerateProviderCode)
		{
			Write("\r\n#pragma warning(push)\r\n#pragma warning(disable: 4691)\r\n::Platform::Collections::Vector<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()\r\n{\r\n    auto lock = _xamlTypesCriticalSection.Lock();\r\n    if(_otherProviders == nullptr)\r\n    {\r\n        auto otherProviders = ref new ::Platform::Collections::Vector<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMetadataProvider^>();\r\n");
			if (base.ProjectInfo.GenerateProviderCode && base.SchemaInfo.OtherMetadataProviders.Any())
			{
				Write("        ");
				Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
				Write("::IXamlMetadataProvider^ provider;\r\n");
				foreach (TypeForCodeGen otherMetadataProvider in base.SchemaInfo.OtherMetadataProviders)
				{
					Write("        provider = ref new ");
					Write(base.ToStringHelper.ToStringWithCulture(otherMetadataProvider.FullName));
					Write("();\r\n        otherProviders->Append(provider); \r\n");
				}
			}
			Write("        _otherProviders = otherProviders;\r\n    }\r\n    return _otherProviders;\r\n}\r\n#pragma warning(pop)\r\n");
		}
		Write("\r\n");
		if (base.ProjectInfo.EnableTypeInfoReflection)
		{
			Write("::XamlTypeInfo::InfoProvider::XamlActivatableType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::GetActivatableTypeForTypeName(::Platform::String^ typeName)\r\n{\r\n");
			if (!base.Model.TypeInfos.Any())
			{
				Write("    // No Local Types\r\n    (void)typeName; // Unused parameter\r\n    return nullptr;\r\n");
			}
			else
			{
				Write("    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);\r\n    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;\r\n    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)\r\n    {\r\n        return nullptr;\r\n    }\r\n    else\r\n    {\r\n        auto activatableType = ref new XamlTypeInfo::InfoProvider::XamlActivatableType();\r\n        activatableType->Activator = pTypeInfo->activator;\r\n        return activatableType;\r\n    }\r\n");
			}
			Write("}\r\n");
		}
		else
		{
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)\r\n{\r\n");
			if (!base.Model.TypeInfos.Any())
			{
				Write("    // No Local Types\r\n    (void)typeName; // Unused parameter\r\n    return nullptr;\r\n");
			}
			else
			{
				Write("    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);\r\n    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;\r\n    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)\r\n    {\r\n        return nullptr;\r\n    }\r\n    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)\r\n    {\r\n        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);\r\n    }\r\n    else\r\n    {\r\n        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(\r\n            this, \r\n            ::Platform::StringReference(pTypeInfo->typeName), \r\n            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L\"\")));\r\n        userType->KindOfType = pTypeInfo->kindofType;\r\n        userType->Activator = pTypeInfo->activator;\r\n        userType->CollectionAdd = pTypeInfo->collectionAdd;\r\n        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;\r\n        userType->FromStringConverter = pTypeInfo->fromStringConverter;\r\n        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);\r\n        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;\r\n        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;\r\n        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;\r\n        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;\r\n        userType->CreateFromStringMethod = nullptr;\r\n");
				if (base.Model.TypeInfos.Where((TypeGenInfo entry) => entry.HasCreateFromStringMethod).Any())
				{
					Write("        if (pTypeInfo->createFromStringIndex != -1)\r\n        {\r\n            userType->CreateFromStringMethod = CreateFromStringMethods[pTypeInfo->createFromStringIndex];\r\n        }\r\n");
				}
				Write("        userType->SetBoxedType(this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->boxedTypeIndex >= 0 ? TypeInfos[pTypeInfo->boxedTypeIndex].typeName : L\"\")));\r\n");
				if (base.Model.MemberInfos.Count() > 0)
				{
					Write("        int nextMemberIndex = pTypeInfo->firstMemberIndex;\r\n        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)\r\n        {\r\n            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));\r\n            nextMemberIndex++;\r\n        }\r\n");
				}
				if (base.Model.EnumValues.Count() > 0)
				{
					Write("        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)\r\n        {\r\n            userType->AddEnumValue(\r\n                ::Platform::StringReference(EnumValues[i].name),\r\n                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));\r\n        }\r\n");
				}
				Write("        return userType;\r\n    }\r\n");
			}
			Write("}\r\n\r\n");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<TypeInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
			Write("::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)\r\n{\r\n    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;\r\n");
			if (!base.Model.MemberInfos.Any())
			{
				Write("    // No Local Properties\r\n    (void)longMemberName; // Unused parameter\r\n");
			}
			else
			{
				Write("    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);\r\n    if (pMemberInfo != nullptr)\r\n    {\r\n        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(\r\n            this,\r\n            ::Platform::StringReference(pMemberInfo->shortName),\r\n            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));\r\n        xamlMember->Getter = pMemberInfo->getter;\r\n        xamlMember->Setter = pMemberInfo->setter;\r\n        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L\"\";\r\n        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;\r\n        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;\r\n        xamlMember->IsAttachable = pMemberInfo->isAttachable;\r\n    }\r\n");
			}
			Write("    return xamlMember;\r\n}\r\n");
		}
		return base.GenerationEnvironment.ToString();
	}

	private void Output_GetTypeInfo()
	{
		Write("const TypeInfo* GetTypeInfo(::Platform::String^ typeName)\r\n{\r\n    auto typeNameLength = typeName->Length();\r\n    if (typeNameLength < _countof(TypeInfoLookup) - 1)\r\n    {\r\n        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)\r\n        {\r\n            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))\r\n            {\r\n                return &TypeInfos[i];\r\n            }\r\n        }\r\n    }\r\n    return nullptr;\r\n}\r\n");
	}
}
