using System.CodeDom.Compiler;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class MoComCppBindingInfoPass2 : CppCX_CodeGenerator<BindingInfoDefinition>
{
	public override string TransformText()
	{
		Write("//------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n//------------------------------------------------------------------------------\r\n");
		if (!string.IsNullOrEmpty(base.ProjectInfo.PrecompiledHeaderFile))
		{
			Write("#include \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.ProjectInfo.PrecompiledHeaderFile));
			Write("\"\r\n");
		}
		Write("#include \"XamlBindingInfo.g.h\"\r\n\r\n// XamlBindings\r\n\r\n::XamlBindingInfo::XamlBindings::XamlBindings(::XamlBindingInfo::IXamlBindings* pBindings)\r\n    : _pBindings(pBindings)\r\n{\r\n    _pBindings->SetOwningBindingsClass(this);\r\n}\r\n\r\n::XamlBindingInfo::XamlBindings::~XamlBindings()\r\n{\r\n    delete _pBindings;\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::Initialize()\r\n{\r\n    if (!this->_pBindings->IsInitialized())\r\n    { \r\n        this->_pBindings->Update();\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::Update()\r\n{\r\n    this->_pBindings->Update();\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::StopTracking()\r\n{\r\n    this->_pBindings->StopTracking();\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::Loading(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::FrameworkElement^, ::Platform::Object^)\r\n{\r\n    this->Initialize();\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::DataContextChanged(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::FrameworkElement^, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DataContextChangedEventArgs^ args)\r\n{\r\n    if (this->_pBindings->SetDataRoot(args->NewValue))\r\n    {\r\n        this->Update();\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::SubscribeForDataContextChanged(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::FrameworkElement^ object)\r\n{\r\n    this->_pBindings->SubscribeForDataContextChanged(object, this);\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::DisconnectUnloadedObject(int connectionId)\r\n{\r\n    this->_pBindings->DisconnectUnloadedObject(connectionId);\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::Connect(int connectionId, ::Platform::Object^ target)\r\n{\r\n    this->_pBindings->Connect(connectionId, target);\r\n}\r\n\r\nbool ::XamlBindingInfo::XamlBindings::ProcessBinding(unsigned int)\r\n{\r\n    throw ref new ::Platform::NotImplementedException();\r\n}\r\n\r\nint ::XamlBindingInfo::XamlBindings::ProcessBindings(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Controls")));
		Write("::ContainerContentChangingEventArgs^ args)\r\n{\r\n    int nextPhase = -1;\r\n    int phase = static_cast<int>(args->Phase);\r\n    if (phase < 0)\r\n    {\r\n        throw ref new ::Platform::InvalidArgumentException();\r\n    }\r\n    this->_pBindings->ProcessBindings(args->Item, args->ItemIndex, phase, &nextPhase);\r\n    return nextPhase;\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::ResetTemplate()\r\n{\r\n    this->_pBindings->Recycle();\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)\r\n{\r\n    this->_pBindings->ProcessBindings(item, itemIndex, phase, nextPhase);\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::Recycle()\r\n{\r\n    this->_pBindings->Recycle();\r\n}\r\n\r\n");
		if (base.ProjectInfo.ShouldGenerateDisableXBind)
		{
			Write("void ::XamlBindingInfo::XamlBindings::Disable(int lineNumber, int columnNumber)\r\n{\r\n    this->_pBindings->Disable(lineNumber, columnNumber);\r\n}\r\n");
		}
		Write("\r\n");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Markup")));
		Write("::IComponentConnector^ ::XamlBindingInfo::XamlBindings::GetBindingConnector(int connectionId, ::Platform::Object^ target)\r\n{\r\n    return this->_pBindings->GetBindingConnector(connectionId, target);\r\n}\r\n\r\n::XamlBindingInfo::XamlBindings^ ::XamlBindingInfo::XamlBindings::GetParent()\r\n{\r\n    return this->_pBindings->GetParent();\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::SetParent(::XamlBindingInfo::XamlBindings^ parent)\r\n{\r\n    this->_pBindings->SetParent(parent);\r\n}\r\n\r\nbool ::XamlBindingInfo::XamlBindings::ContainsElement(int connectionId)\r\n{\r\n    return this->_pBindings->ContainsElement(connectionId);\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindings::RegisterForElementConnection(int connectionId, ::XamlBindingInfo::XamlBindings^ connector)\r\n{\r\n    this->_pBindings->RegisterForElementConnection(connectionId, connector);\r\n}\r\n\r\n// XamlBindingTrackingBase\r\n\r\n::XamlBindingInfo::XamlBindingTrackingBase::XamlBindingTrackingBase()\r\n{\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::SetListener(::XamlBindingInfo::IXamlBindingTracking* pBindings)\r\n{\r\n    this->_pBindingsTrackingWeakRef = pBindings;\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::PropertyChanged(Platform::Object^ sender, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::PropertyChangedEventArgs^ e)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->PropertyChanged(sender, e);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::CollectionChanged(::Platform::Object^ sender, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Interop")));
		Write("::NotifyCollectionChangedEventArgs^ e)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->CollectionChanged(sender, e);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::DependencyPropertyChanged(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject^ sender, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyProperty^ prop)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->DependencyPropertyChanged(sender, prop);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::VectorChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IVectorChangedEventArgs^ e)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->VectorChanged(sender, e);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::MapChanged(::Platform::Object^ sender, ::Windows::Foundation::Collections::IMapChangedEventArgs<::Platform::String^>^ e)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->MapChanged(sender, e);\r\n    }\r\n}\r\n");
		if (base.ProjectInfo.IsInputValidationEnabled)
		{
			Write("\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::ErrorsChanged(::Platform::Object^ sender, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::DataErrorsChangedEventArgs^ e)\r\n{\r\n    if (this->_pBindingsTrackingWeakRef != nullptr)\r\n    {\r\n        this->_pBindingsTrackingWeakRef->ErrorsChanged(sender, e);\r\n    }\r\n}\r\n");
		}
		Write("\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdatePropertyChangedListener(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::INotifyPropertyChanged^ obj, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::INotifyPropertyChanged^* pCache, ::Windows::Foundation::EventRegistrationToken* pToken)\r\n{\r\n    if (*pCache != nullptr && !(*pCache)->Equals(obj))\r\n    {\r\n        (*pCache)->PropertyChanged -= *pToken;\r\n        *pCache = nullptr;\r\n    }\r\n\r\n    if (*pCache == nullptr && obj != nullptr)\r\n    {\r\n        *pCache = obj;\r\n        *pToken = obj->PropertyChanged += ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::PropertyChangedEventHandler(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::PropertyChanged);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdatePropertyChangedListener(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::INotifyPropertyChanged^ obj, ::Platform::WeakReference& cacheRef, ::Windows::Foundation::EventRegistrationToken* pToken)\r\n{\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::INotifyPropertyChanged^ cache = cacheRef.Resolve<");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::INotifyPropertyChanged>();\r\n    if (cache != nullptr && !cache->Equals(obj))\r\n    {\r\n        cache->PropertyChanged -= *pToken;\r\n        cache = nullptr;\r\n        cacheRef = nullptr;\r\n    }\r\n\r\n    if (cache == nullptr && obj != nullptr)\r\n    {\r\n        cacheRef = cache = obj;\r\n        *pToken = obj->PropertyChanged += ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
		Write("::PropertyChangedEventHandler(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::PropertyChanged);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdateCollectionChangedListener(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Interop")));
		Write("::INotifyCollectionChanged^ obj, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Interop")));
		Write("::INotifyCollectionChanged^* pCache, ::Windows::Foundation::EventRegistrationToken* pToken)\r\n{\r\n    if (*pCache != nullptr && !(*pCache)->Equals(obj))\r\n    {\r\n        (*pCache)->CollectionChanged -= *pToken;\r\n        *pCache = nullptr;\r\n    }\r\n\r\n    if (*pCache == nullptr && obj != nullptr)\r\n    {\r\n        *pCache = obj;\r\n        *pToken = obj->CollectionChanged += ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Interop")));
		Write("::NotifyCollectionChangedEventHandler(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::CollectionChanged);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdateDependencyPropertyChangedListener(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject^ obj, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyProperty^ property, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject^* pCache, __int64* pToken)\r\n{\r\n    if (*pCache != nullptr && !(*pCache)->Equals(obj))\r\n    {\r\n        (*pCache)->UnregisterPropertyChangedCallback(property, *pToken);\r\n        *pCache = nullptr;\r\n    }\r\n\r\n    if (*pCache == nullptr && obj != nullptr)\r\n    {\r\n        *pCache = obj;\r\n        *pToken = obj->RegisterPropertyChangedCallback(property, ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyPropertyChangedCallback(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::DependencyPropertyChanged));\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdateDependencyPropertyChangedListener(");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject^ obj, ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyProperty^ property, ::Platform::WeakReference& cacheRef, __int64* pToken)\r\n{\r\n    ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject^ cache = cacheRef.Resolve<");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyObject>();\r\n    if (cache != nullptr && !cache->Equals(obj))\r\n    {\r\n        cache->UnregisterPropertyChangedCallback(property, *pToken);\r\n        cache = nullptr;\r\n        cacheRef = nullptr;\r\n    }\r\n\r\n    if (cache == nullptr && obj != nullptr)\r\n    {\r\n        cacheRef = cache = obj;\r\n        *pToken = obj->RegisterPropertyChangedCallback(property, ref new ");
		Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml")));
		Write("::DependencyPropertyChangedCallback(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::DependencyPropertyChanged));\r\n    }\r\n}\r\n");
		if (base.ProjectInfo.IsInputValidationEnabled)
		{
			Write("void ::XamlBindingInfo::XamlBindingTrackingBase::UpdateErrorsChangedListener(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::INotifyDataErrorInfo^ obj, ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::INotifyDataErrorInfo^* pCache, ::Windows::Foundation::EventRegistrationToken* pToken)\r\n{\r\n    if (*pCache != nullptr && !(*pCache)->Equals(obj))\r\n    {\r\n        (*pCache)->ErrorsChanged -= *pToken;\r\n        *pCache = nullptr;\r\n    }\r\n\r\n    if (*pCache == nullptr && obj != nullptr)\r\n    {\r\n        *pCache = obj;\r\n        *pToken = obj->ErrorsChanged += ref new ::Windows::Foundation::EventHandler<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::DataErrorsChangedEventArgs^>(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::ErrorsChanged);\r\n    }\r\n}\r\n\r\nvoid ::XamlBindingInfo::XamlBindingTrackingBase::UpdateErrorsChangedListener(");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::INotifyDataErrorInfo^ obj, ::Platform::WeakReference& cacheRef, ::Windows::Foundation::EventRegistrationToken* pToken)\r\n{\r\n    ");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::INotifyDataErrorInfo^ cache = cacheRef.Resolve<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::INotifyDataErrorInfo>();\r\n    if (cache != nullptr && !cache->Equals(obj))\r\n    {\r\n        cache->ErrorsChanged -= *pToken;\r\n        cache = nullptr;\r\n        cacheRef = nullptr;\r\n    }\r\n\r\n    if (cache == nullptr && obj != nullptr)\r\n    {\r\n        cacheRef = cache = obj;\r\n        *pToken = obj->ErrorsChanged += ref new ::Windows::Foundation::EventHandler<");
			Write(base.ToStringHelper.ToStringWithCulture(CppCX_CodeGenerator<BindingInfoDefinition>.Projection("Microsoft.UI.Xaml.Data")));
			Write("::DataErrorsChangedEventArgs^>(\r\n            this, &::XamlBindingInfo::XamlBindingTrackingBase::ErrorsChanged);\r\n    }\r\n}\r\n");
		}
		return base.GenerationEnvironment.ToString();
	}
}
