using System.CodeDom.Compiler;
using System.Linq;

namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen;

[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
internal class VisualBasicPagePass1 : VB_CodeGenerator<PageDefinition>
{
	public override string TransformText()
	{
		foreach (FileNameAndChecksumPair xamlFileFullPathAndCheckSum in base.Model.XamlFileFullPathAndCheckSums)
		{
			Write("#ExternalChecksum(\"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.FileName));
			Write("\", \"");
			Write(base.ToStringHelper.ToStringWithCulture(base.Model.ChecksumAlgorithmGuid));
			Write("\", \"");
			Write(base.ToStringHelper.ToStringWithCulture(xamlFileFullPathAndCheckSum.Checksum));
			Write("\")\r\n");
		}
		Write("'------------------------------------------------------------------------------\r\n' <auto-generated>\r\n'     This code was generated by a tool.\r\n'\r\n'     Changes to this file may cause incorrect behavior and will be lost if\r\n'     the code is regenerated.\r\n' </auto-generated>\r\n'------------------------------------------------------------------------------\r\n\r\nOption Strict Off\r\nOption Explicit On\r\n\r\n\r\nNamespace ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize(base.Model.CodeInfo.ClassName.Namespace)));
		Write("\r\n\r\n    <Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>  _\r\n    Partial Class ");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("\r\n        Inherits ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize(base.Model.CodeInfo.BaseTypeName)));
		Write("\r\n\r\n");
		Output_xProperties();
		Write("\r\n");
		Output_FieldDefinitions();
		Write("\r\n        Private _contentLoaded As Boolean\r\n\r\n");
		Output_InitializeComponent();
		Write("\r\n");
		if (base.Model.CodeInfo.BindStatus != BindStatus.None)
		{
			Output_BindingsHeader();
		}
		Write("\r\n    End Class\r\n\r\nEnd Namespace\r\n\r\n");
		return base.GenerationEnvironment.ToString();
	}

	private void Output_InitializeComponent()
	{
		string loadComponentUri = base.Model.GetLoadComponentUri(base.Model.CodeInfo.PriIndexName, base.Model.CodeInfo.BaseApparentRelativePath);
		Write("        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
		Write("\r\n        Public Sub InitializeComponent()\r\n");
		if (base.Model.CodeInfo.PerXamlFileInfo.Count > 1)
		{
			Write("            Me.InitializeComponent(Nothing)\r\n        End Sub\r\n\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
			Write("\r\n        Public Sub InitializeComponent(ByVal resourceLocator As Global.System.Uri)\r\n");
		}
		Write("            If _contentLoaded Then\r\n                Return\r\n            End If\r\n            _contentLoaded = true\r\n\r\n");
		if (base.Model.XProperties.Any())
		{
			Write("        InitializeXProperties()\r\n");
		}
		if (base.Model.CodeInfo.PerXamlFileInfo.Count > 1)
		{
			Write("            if resourceLocator Is Nothing Then\r\n                resourceLocator = new Global.System.Uri(\"");
			Write(base.ToStringHelper.ToStringWithCulture(loadComponentUri));
			Write("\")\r\n            End If\r\n");
		}
		else
		{
			Write("            Dim resourceLocator As New Global.System.Uri(\"");
			Write(base.ToStringHelper.ToStringWithCulture(loadComponentUri));
			Write("\")\r\n");
		}
		string objectToConvert = (base.ProjectInfo.IsLibrary ? "Nested" : "Application");
		if (!string.IsNullOrEmpty(base.Model.CodeInfo.XamlComponentResourceLocation))
		{
			Write("            ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
			Write(".Application.LoadComponent(Me, resourceLocator, ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Controls.Primitives")));
			Write(".ComponentResourceLocation.");
			Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.XamlComponentResourceLocation));
			Write(")\r\n");
		}
		else
		{
			Write("            ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
			Write(".Application.LoadComponent(Me, resourceLocator, ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Controls.Primitives")));
			Write(".ComponentResourceLocation.");
			Write(base.ToStringHelper.ToStringWithCulture(objectToConvert));
			Write(")\r\n");
		}
		Write("        End Sub\r\n\r\n        Partial Private Sub UnloadObject(unloadableObject As ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml")));
		Write(".DependencyObject)\r\n        End Sub\r\n\r\n");
	}

	private void Output_FieldDefinitions()
	{
		foreach (FieldDefinition fieldDeclaration in base.Model.CodeInfo.FieldDeclarations)
		{
			Write("        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(fieldDeclaration.FieldModifier));
			Write(" WithEvents ");
			Write(base.ToStringHelper.ToStringWithCulture(fieldDeclaration.FieldName));
			Write(" As ");
			Write(base.ToStringHelper.ToStringWithCulture(Globalize(fieldDeclaration.FieldTypeName)));
			Write("\r\n");
		}
	}

	private void Output_BindingsHeader()
	{
		Write("        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        Private Interface I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_Bindings\r\n            Sub Initialize()\r\n            Sub Update()\r\n            Sub StopTracking()\r\n            Sub DisconnectUnloadedObject(connectionId As Integer)\r\n        End Interface\r\n\r\n        Private Interface I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_BindingsScopeConnector\r\n            Property Parent() As Global.System.WeakReference\r\n            Function ContainsElement(connectionId As Integer) As Boolean\r\n            Sub RegisterForElementConnection(connectionId As Integer, connector As ");
		Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Markup")));
		Write(".IComponentConnector)\r\n        End Interface\r\n\r\n        ");
		Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
		Write("\r\n        Private Bindings As I");
		Write(base.ToStringHelper.ToStringWithCulture(base.Model.CodeInfo.ClassName.ShortName));
		Write("_Bindings\r\n");
	}

	private void Output_xProperties()
	{
		if (base.Model.XProperties.Any())
		{
			Write("        Partial Private Sub InitializeXProperties\r\n        End Sub\r\n\r\n");
		}
		foreach (xProperty xProperty in base.Model.XProperties)
		{
			Write("        ' ");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.CodegenComment));
			Write("\r\n        ");
			Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
			Write("\r\n        Private  _");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write(" As Global.");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
			Write("\r\n");
			if (!xProperty.IsReadOnly)
			{
				Write("        ");
				Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
				Write("\r\n        Public Event ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write(" As ");
				Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Data")));
				Write(".PropertyChangedEventHandler        \r\n\r\n        ");
				Write(base.ToStringHelper.ToStringWithCulture(base.GeneratedCodeAttribute));
				Write("\r\n        ");
				Write(base.ToStringHelper.ToStringWithCulture(base.DebuggerNonUserCodeAttribute));
				Write("\r\n        Public Property ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write("() As Global.");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
				Write("\r\n");
			}
			else
			{
				Write("        Public ReadOnly Property ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write("() As Global.");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
				Write("\r\n");
			}
			Write("            Get\r\n                Return _");
			Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
			Write("\r\n            End Get\r\n");
			if (!xProperty.IsReadOnly)
			{
				Write("            Set(ByVal Value As Global.");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.FullTypeName));
				Write(")\r\n                If Not _");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write(" Is Value Then\r\n                    _");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write(" = Value\r\n                    RaiseEvent ");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.ChangedHandler));
				Write("(Me, New ");
				Write(base.ToStringHelper.ToStringWithCulture(Globalize("Microsoft.UI.Xaml.Data")));
				Write(".PropertyChangedEventArgs(\"");
				Write(base.ToStringHelper.ToStringWithCulture(xProperty.Name));
				Write("\"))\r\n                End If\r\n            End Set\r\n");
			}
			Write("        End Property\r\n\r\n");
		}
	}
}
