//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/XamlCompiler/Grammars/BindingPath/BindingPath.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class BindingPathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, WS=9, 
		ESCAPEDQUOTE=10, QUOTE=11, DOUBLE_QUOTE=12, TRUE=13, FALSE=14, NULL=15, 
		Digits=16, QuotedString=17, IDENTIFIER=18;
	public const int
		RULE_program = 0, RULE_decimal_value = 1, RULE_boolean_value = 2, RULE_namespace_qualifier = 3, 
		RULE_static_type = 4, RULE_attached_expr = 5, RULE_cast_expr = 6, RULE_function = 7, 
		RULE_path = 8, RULE_function_param = 9;
	public static readonly string[] ruleNames = {
		"program", "decimal_value", "boolean_value", "namespace_qualifier", "static_type", 
		"attached_expr", "cast_expr", "function", "path", "function_param"
	};

	private static readonly string[] _LiteralNames = {
		null, "'-'", "'.'", "':'", "'('", "')'", "','", "'['", "']'", null, null, 
		"'''", "'\"'", "'x:True'", "'x:False'", "'x:Null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "WS", "ESCAPEDQUOTE", 
		"QUOTE", "DOUBLE_QUOTE", "TRUE", "FALSE", "NULL", "Digits", "QuotedString", 
		"IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BindingPath.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static BindingPathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public BindingPathParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public BindingPathParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(BindingPathParser.Eof, 0); }
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 20;
			path(0);
			State = 21;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Decimal_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Digits() { return GetTokens(BindingPathParser.Digits); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits(int i) {
			return GetToken(BindingPathParser.Digits, i);
		}
		public Decimal_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decimal_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterDecimal_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitDecimal_value(this);
		}
	}

	[RuleVersion(0)]
	public Decimal_valueContext decimal_value() {
		Decimal_valueContext _localctx = new Decimal_valueContext(Context, State);
		EnterRule(_localctx, 2, RULE_decimal_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 23;
				Match(T__0);
				}
			}

			State = 26;
			Match(Digits);
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 27;
				Match(T__1);
				State = 28;
				Match(Digits);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Boolean_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(BindingPathParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(BindingPathParser.FALSE, 0); }
		public Boolean_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolean_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterBoolean_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitBoolean_value(this);
		}
	}

	[RuleVersion(0)]
	public Boolean_valueContext boolean_value() {
		Boolean_valueContext _localctx = new Boolean_valueContext(Context, State);
		EnterRule(_localctx, 4, RULE_boolean_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			_la = TokenStream.LA(1);
			if ( !(_la==TRUE || _la==FALSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Namespace_qualifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public Namespace_qualifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace_qualifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterNamespace_qualifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitNamespace_qualifier(this);
		}
	}

	[RuleVersion(0)]
	public Namespace_qualifierContext namespace_qualifier() {
		Namespace_qualifierContext _localctx = new Namespace_qualifierContext(Context, State);
		EnterRule(_localctx, 6, RULE_namespace_qualifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			Match(IDENTIFIER);
			State = 34;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Static_typeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_qualifierContext namespace_qualifier() {
			return GetRuleContext<Namespace_qualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public Static_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_static_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterStatic_type(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitStatic_type(this);
		}
	}

	[RuleVersion(0)]
	public Static_typeContext static_type() {
		Static_typeContext _localctx = new Static_typeContext(Context, State);
		EnterRule(_localctx, 8, RULE_static_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			namespace_qualifier();
			State = 37;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Attached_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Static_typeContext static_type() {
			return GetRuleContext<Static_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(BindingPathParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(BindingPathParser.IDENTIFIER, i);
		}
		public Attached_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attached_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterAttached_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitAttached_expr(this);
		}
	}

	[RuleVersion(0)]
	public Attached_exprContext attached_expr() {
		Attached_exprContext _localctx = new Attached_exprContext(Context, State);
		EnterRule(_localctx, 10, RULE_attached_expr);
		try {
			State = 50;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39;
				Match(T__3);
				State = 40;
				static_type();
				State = 41;
				Match(T__1);
				State = 42;
				Match(IDENTIFIER);
				State = 43;
				Match(T__4);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 45;
				Match(T__3);
				State = 46;
				Match(IDENTIFIER);
				State = 47;
				Match(T__1);
				State = 48;
				Match(IDENTIFIER);
				State = 49;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cast_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Static_typeContext static_type() {
			return GetRuleContext<Static_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public Cast_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cast_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterCast_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitCast_expr(this);
		}
	}

	[RuleVersion(0)]
	public Cast_exprContext cast_expr() {
		Cast_exprContext _localctx = new Cast_exprContext(Context, State);
		EnterRule(_localctx, 12, RULE_cast_expr);
		try {
			State = 59;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 52;
				Match(T__3);
				State = 53;
				static_type();
				State = 54;
				Match(T__4);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 56;
				Match(T__3);
				State = 57;
				Match(IDENTIFIER);
				State = 58;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_paramContext[] function_param() {
			return GetRuleContexts<Function_paramContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_paramContext function_param(int i) {
			return GetRuleContext<Function_paramContext>(i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 14, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			Match(IDENTIFIER);
			State = 62;
			Match(T__3);
			State = 64;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 516114L) != 0)) {
				{
				State = 63;
				function_param();
				}
			}

			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 66;
				Match(T__5);
				State = 67;
				function_param();
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 73;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathContext : ParserRuleContext {
		public Microsoft.UI.Xaml.Markup.Compiler.BindPathStep PathStep;
		public PathContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_path; } }
	 
		public PathContext() { }
		public virtual void CopyFrom(PathContext context) {
			base.CopyFrom(context);
			this.PathStep = context.PathStep;
		}
	}
	public partial class PathStaticFuctionContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Static_typeContext static_type() {
			return GetRuleContext<Static_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public PathStaticFuctionContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathStaticFuction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathStaticFuction(this);
		}
	}
	public partial class PathCastContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Cast_exprContext cast_expr() {
			return GetRuleContext<Cast_exprContext>(0);
		}
		public PathCastContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathCast(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathCast(this);
		}
	}
	public partial class PathPathToFunctionContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public PathPathToFunctionContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathPathToFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathPathToFunction(this);
		}
	}
	public partial class PathIndexerContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(BindingPathParser.Digits, 0); }
		public PathIndexerContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathIndexer(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathIndexer(this);
		}
	}
	public partial class PathCastInvalidContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Attached_exprContext attached_expr() {
			return GetRuleContext<Attached_exprContext>(0);
		}
		public PathCastInvalidContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathCastInvalid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathCastInvalid(this);
		}
	}
	public partial class PathCastPathParenContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Cast_exprContext cast_expr() {
			return GetRuleContext<Cast_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		public PathCastPathParenContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathCastPathParen(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathCastPathParen(this);
		}
	}
	public partial class PathFunctionContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public PathFunctionContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathFunction(this);
		}
	}
	public partial class PathStringIndexerContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QuotedString() { return GetToken(BindingPathParser.QuotedString, 0); }
		public PathStringIndexerContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathStringIndexer(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathStringIndexer(this);
		}
	}
	public partial class PathIdentifierContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public PathIdentifierContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathIdentifier(this);
		}
	}
	public partial class PathCastPathContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Cast_exprContext cast_expr() {
			return GetRuleContext<Cast_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		public PathCastPathContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathCastPath(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathCastPath(this);
		}
	}
	public partial class PathStaticIdentifierContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public Static_typeContext static_type() {
			return GetRuleContext<Static_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public PathStaticIdentifierContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathStaticIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathStaticIdentifier(this);
		}
	}
	public partial class PathDotIdentifierContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(BindingPathParser.IDENTIFIER, 0); }
		public PathDotIdentifierContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathDotIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathDotIdentifier(this);
		}
	}
	public partial class PathDotAttachedContext : PathContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Attached_exprContext attached_expr() {
			return GetRuleContext<Attached_exprContext>(0);
		}
		public PathDotAttachedContext(PathContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterPathDotAttached(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitPathDotAttached(this);
		}
	}

	[RuleVersion(0)]
	public PathContext path() {
		return path(0);
	}

	private PathContext path(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		PathContext _localctx = new PathContext(Context, _parentState);
		PathContext _prevctx = _localctx;
		int _startState = 16;
		EnterRecursionRule(_localctx, 16, RULE_path, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				_localctx = new PathIdentifierContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 76;
				Match(IDENTIFIER);
				}
				break;
			case 2:
				{
				_localctx = new PathStaticIdentifierContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 77;
				static_type();
				State = 78;
				Match(T__1);
				State = 79;
				Match(IDENTIFIER);
				}
				break;
			case 3:
				{
				_localctx = new PathCastInvalidContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 81;
				attached_expr();
				}
				break;
			case 4:
				{
				_localctx = new PathCastContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 82;
				cast_expr();
				}
				break;
			case 5:
				{
				_localctx = new PathCastPathContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 83;
				cast_expr();
				State = 84;
				path(5);
				}
				break;
			case 6:
				{
				_localctx = new PathCastPathParenContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 86;
				Match(T__3);
				State = 87;
				cast_expr();
				State = 88;
				path(0);
				State = 89;
				Match(T__4);
				}
				break;
			case 7:
				{
				_localctx = new PathFunctionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 91;
				function();
				}
				break;
			case 8:
				{
				_localctx = new PathStaticFuctionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 92;
				static_type();
				State = 93;
				Match(T__1);
				State = 94;
				function();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 117;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 115;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
					case 1:
						{
						_localctx = new PathDotIdentifierContext(new PathContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_path);
						State = 98;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 99;
						Match(T__1);
						State = 100;
						Match(IDENTIFIER);
						}
						break;
					case 2:
						{
						_localctx = new PathIndexerContext(new PathContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_path);
						State = 101;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 102;
						Match(T__6);
						State = 103;
						Match(Digits);
						State = 104;
						Match(T__7);
						}
						break;
					case 3:
						{
						_localctx = new PathStringIndexerContext(new PathContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_path);
						State = 105;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 106;
						Match(T__6);
						State = 107;
						Match(QuotedString);
						State = 108;
						Match(T__7);
						}
						break;
					case 4:
						{
						_localctx = new PathDotAttachedContext(new PathContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_path);
						State = 109;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 110;
						Match(T__1);
						State = 111;
						attached_expr();
						}
						break;
					case 5:
						{
						_localctx = new PathPathToFunctionContext(new PathContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_path);
						State = 112;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 113;
						Match(T__1);
						State = 114;
						function();
						}
						break;
					}
					} 
				}
				State = 119;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Function_paramContext : ParserRuleContext {
		public Microsoft.UI.Xaml.Markup.Compiler.FunctionParam Param;
		public Function_paramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_param; } }
	 
		public Function_paramContext() { }
		public virtual void CopyFrom(Function_paramContext context) {
			base.CopyFrom(context);
			this.Param = context.Param;
		}
	}
	public partial class FunctionParamNumberContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public Decimal_valueContext decimal_value() {
			return GetRuleContext<Decimal_valueContext>(0);
		}
		public FunctionParamNumberContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParamNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParamNumber(this);
		}
	}
	public partial class FunctionParamBoolContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public Boolean_valueContext boolean_value() {
			return GetRuleContext<Boolean_valueContext>(0);
		}
		public FunctionParamBoolContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParamBool(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParamBool(this);
		}
	}
	public partial class FunctionParameterInvalidContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public FunctionParameterInvalidContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParameterInvalid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParameterInvalid(this);
		}
	}
	public partial class FunctionParamStringContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QuotedString() { return GetToken(BindingPathParser.QuotedString, 0); }
		public FunctionParamStringContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParamString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParamString(this);
		}
	}
	public partial class FunctionParamPathContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathContext path() {
			return GetRuleContext<PathContext>(0);
		}
		public FunctionParamPathContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParamPath(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParamPath(this);
		}
	}
	public partial class FunctionParamNullValueContext : Function_paramContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(BindingPathParser.NULL, 0); }
		public FunctionParamNullValueContext(Function_paramContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.EnterFunctionParamNullValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IBindingPathListener typedListener = listener as IBindingPathListener;
			if (typedListener != null) typedListener.ExitFunctionParamNullValue(this);
		}
	}

	[RuleVersion(0)]
	public Function_paramContext function_param() {
		Function_paramContext _localctx = new Function_paramContext(Context, State);
		EnterRule(_localctx, 18, RULE_function_param);
		try {
			State = 126;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				_localctx = new FunctionParameterInvalidContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				function();
				}
				break;
			case 2:
				_localctx = new FunctionParamPathContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 121;
				path(0);
				}
				break;
			case 3:
				_localctx = new FunctionParamBoolContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 122;
				boolean_value();
				}
				break;
			case 4:
				_localctx = new FunctionParamNumberContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 123;
				decimal_value();
				}
				break;
			case 5:
				_localctx = new FunctionParamStringContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 124;
				Match(QuotedString);
				}
				break;
			case 6:
				_localctx = new FunctionParamNullValueContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 125;
				Match(NULL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 8: return path_sempred((PathContext)_localctx, predIndex);
		}
		return true;
	}
	private bool path_sempred(PathContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 12);
		case 1: return Precpred(Context, 10);
		case 2: return Precpred(Context, 9);
		case 3: return Precpred(Context, 8);
		case 4: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,18,129,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,1,3,1,25,8,1,1,1,1,1,1,1,3,1,30,8,1,
		1,2,1,2,1,3,1,3,1,3,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,3,5,51,8,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,60,8,6,1,7,1,7,1,7,3,
		7,65,8,7,1,7,1,7,5,7,69,8,7,10,7,12,7,72,9,7,1,7,1,7,1,8,1,8,1,8,1,8,1,
		8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,3,8,
		97,8,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,
		1,8,5,8,116,8,8,10,8,12,8,119,9,8,1,9,1,9,1,9,1,9,1,9,1,9,3,9,127,8,9,
		1,9,0,1,16,10,0,2,4,6,8,10,12,14,16,18,0,1,1,0,13,14,141,0,20,1,0,0,0,
		2,24,1,0,0,0,4,31,1,0,0,0,6,33,1,0,0,0,8,36,1,0,0,0,10,50,1,0,0,0,12,59,
		1,0,0,0,14,61,1,0,0,0,16,96,1,0,0,0,18,126,1,0,0,0,20,21,3,16,8,0,21,22,
		5,0,0,1,22,1,1,0,0,0,23,25,5,1,0,0,24,23,1,0,0,0,24,25,1,0,0,0,25,26,1,
		0,0,0,26,29,5,16,0,0,27,28,5,2,0,0,28,30,5,16,0,0,29,27,1,0,0,0,29,30,
		1,0,0,0,30,3,1,0,0,0,31,32,7,0,0,0,32,5,1,0,0,0,33,34,5,18,0,0,34,35,5,
		3,0,0,35,7,1,0,0,0,36,37,3,6,3,0,37,38,5,18,0,0,38,9,1,0,0,0,39,40,5,4,
		0,0,40,41,3,8,4,0,41,42,5,2,0,0,42,43,5,18,0,0,43,44,5,5,0,0,44,51,1,0,
		0,0,45,46,5,4,0,0,46,47,5,18,0,0,47,48,5,2,0,0,48,49,5,18,0,0,49,51,5,
		5,0,0,50,39,1,0,0,0,50,45,1,0,0,0,51,11,1,0,0,0,52,53,5,4,0,0,53,54,3,
		8,4,0,54,55,5,5,0,0,55,60,1,0,0,0,56,57,5,4,0,0,57,58,5,18,0,0,58,60,5,
		5,0,0,59,52,1,0,0,0,59,56,1,0,0,0,60,13,1,0,0,0,61,62,5,18,0,0,62,64,5,
		4,0,0,63,65,3,18,9,0,64,63,1,0,0,0,64,65,1,0,0,0,65,70,1,0,0,0,66,67,5,
		6,0,0,67,69,3,18,9,0,68,66,1,0,0,0,69,72,1,0,0,0,70,68,1,0,0,0,70,71,1,
		0,0,0,71,73,1,0,0,0,72,70,1,0,0,0,73,74,5,5,0,0,74,15,1,0,0,0,75,76,6,
		8,-1,0,76,97,5,18,0,0,77,78,3,8,4,0,78,79,5,2,0,0,79,80,5,18,0,0,80,97,
		1,0,0,0,81,97,3,10,5,0,82,97,3,12,6,0,83,84,3,12,6,0,84,85,3,16,8,5,85,
		97,1,0,0,0,86,87,5,4,0,0,87,88,3,12,6,0,88,89,3,16,8,0,89,90,5,5,0,0,90,
		97,1,0,0,0,91,97,3,14,7,0,92,93,3,8,4,0,93,94,5,2,0,0,94,95,3,14,7,0,95,
		97,1,0,0,0,96,75,1,0,0,0,96,77,1,0,0,0,96,81,1,0,0,0,96,82,1,0,0,0,96,
		83,1,0,0,0,96,86,1,0,0,0,96,91,1,0,0,0,96,92,1,0,0,0,97,117,1,0,0,0,98,
		99,10,12,0,0,99,100,5,2,0,0,100,116,5,18,0,0,101,102,10,10,0,0,102,103,
		5,7,0,0,103,104,5,16,0,0,104,116,5,8,0,0,105,106,10,9,0,0,106,107,5,7,
		0,0,107,108,5,17,0,0,108,116,5,8,0,0,109,110,10,8,0,0,110,111,5,2,0,0,
		111,116,3,10,5,0,112,113,10,2,0,0,113,114,5,2,0,0,114,116,3,14,7,0,115,
		98,1,0,0,0,115,101,1,0,0,0,115,105,1,0,0,0,115,109,1,0,0,0,115,112,1,0,
		0,0,116,119,1,0,0,0,117,115,1,0,0,0,117,118,1,0,0,0,118,17,1,0,0,0,119,
		117,1,0,0,0,120,127,3,14,7,0,121,127,3,16,8,0,122,127,3,4,2,0,123,127,
		3,2,1,0,124,127,5,17,0,0,125,127,5,15,0,0,126,120,1,0,0,0,126,121,1,0,
		0,0,126,122,1,0,0,0,126,123,1,0,0,0,126,124,1,0,0,0,126,125,1,0,0,0,127,
		19,1,0,0,0,10,24,29,50,59,64,70,96,115,117,126
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
