//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/XamlCompiler/Grammars/SuccinctCollectionSyntax/SuccinctCollectionSyntax.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class SuccinctCollectionSyntaxParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SINGLE_QUOTE=1, DOUBLE_QUOTE=2, OPEN_SQUARE_BRACE=3, CLOSE_SQUARE_BRACE=4, 
		CHARACTER=5, COMMA=6, BACKSLASH=7, RESERVED_SYMBOL=8, QUOTE=9;
	public const int
		RULE_program = 0, RULE_items = 1, RULE_z = 2, RULE_item = 3, RULE_text = 4, 
		RULE_literal_text = 5, RULE_sequence = 6;
	public static readonly string[] ruleNames = {
		"program", "items", "z", "item", "text", "literal_text", "sequence"
	};

	private static readonly string[] _LiteralNames = {
		null, "'''", "'\"'", "'['", "']'", null, "','", "'\\'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SINGLE_QUOTE", "DOUBLE_QUOTE", "OPEN_SQUARE_BRACE", "CLOSE_SQUARE_BRACE", 
		"CHARACTER", "COMMA", "BACKSLASH", "RESERVED_SYMBOL", "QUOTE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SuccinctCollectionSyntax.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SuccinctCollectionSyntaxParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SuccinctCollectionSyntaxParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SuccinctCollectionSyntaxParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ItemsContext items() {
			return GetRuleContext<ItemsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SuccinctCollectionSyntaxParser.Eof, 0); }
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 14;
			items();
			State = 15;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ItemsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ItemContext item() {
			return GetRuleContext<ItemContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ZContext z() {
			return GetRuleContext<ZContext>(0);
		}
		public ItemsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_items; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterItems(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitItems(this);
		}
	}

	[RuleVersion(0)]
	public ItemsContext items() {
		ItemsContext _localctx = new ItemsContext(Context, State);
		EnterRule(_localctx, 2, RULE_items);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			item();
			State = 18;
			z();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ZContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SuccinctCollectionSyntaxParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ItemContext item() {
			return GetRuleContext<ItemContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ZContext z() {
			return GetRuleContext<ZContext>(0);
		}
		public ZContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_z; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterZ(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitZ(this);
		}
	}

	[RuleVersion(0)]
	public ZContext z() {
		ZContext _localctx = new ZContext(Context, State);
		EnterRule(_localctx, 4, RULE_z);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COMMA) {
				{
				State = 20;
				Match(COMMA);
				State = 21;
				item();
				State = 22;
				z();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ItemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_QUOTE() { return GetTokens(SuccinctCollectionSyntaxParser.SINGLE_QUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_QUOTE(int i) {
			return GetToken(SuccinctCollectionSyntaxParser.SINGLE_QUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Literal_textContext literal_text() {
			return GetRuleContext<Literal_textContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOUBLE_QUOTE() { return GetTokens(SuccinctCollectionSyntaxParser.DOUBLE_QUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_QUOTE(int i) {
			return GetToken(SuccinctCollectionSyntaxParser.DOUBLE_QUOTE, i);
		}
		public ItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterItem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitItem(this);
		}
	}

	[RuleVersion(0)]
	public ItemContext item() {
		ItemContext _localctx = new ItemContext(Context, State);
		EnterRule(_localctx, 6, RULE_item);
		try {
			State = 35;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Eof:
			case CHARACTER:
			case COMMA:
			case BACKSLASH:
				EnterOuterAlt(_localctx, 1);
				{
				State = 26;
				text();
				}
				break;
			case SINGLE_QUOTE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 27;
				Match(SINGLE_QUOTE);
				State = 28;
				literal_text();
				State = 29;
				Match(SINGLE_QUOTE);
				}
				break;
			case DOUBLE_QUOTE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 31;
				Match(DOUBLE_QUOTE);
				State = 32;
				literal_text();
				State = 33;
				Match(DOUBLE_QUOTE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARACTER() { return GetToken(SuccinctCollectionSyntaxParser.CHARACTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BACKSLASH() { return GetToken(SuccinctCollectionSyntaxParser.BACKSLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SequenceContext sequence() {
			return GetRuleContext<SequenceContext>(0);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitText(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 8, RULE_text);
		int _la;
		try {
			State = 45;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Eof:
			case CHARACTER:
			case COMMA:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==CHARACTER) {
					{
					State = 37;
					Match(CHARACTER);
					State = 38;
					text();
					}
				}

				}
				break;
			case BACKSLASH:
				EnterOuterAlt(_localctx, 2);
				{
				State = 41;
				Match(BACKSLASH);
				State = 42;
				sequence();
				State = 43;
				text();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Literal_textContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARACTER() { return GetToken(SuccinctCollectionSyntaxParser.CHARACTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Literal_textContext literal_text() {
			return GetRuleContext<Literal_textContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BACKSLASH() { return GetToken(SuccinctCollectionSyntaxParser.BACKSLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SequenceContext sequence() {
			return GetRuleContext<SequenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESERVED_SYMBOL() { return GetToken(SuccinctCollectionSyntaxParser.RESERVED_SYMBOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SuccinctCollectionSyntaxParser.COMMA, 0); }
		public Literal_textContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterLiteral_text(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitLiteral_text(this);
		}
	}

	[RuleVersion(0)]
	public Literal_textContext literal_text() {
		Literal_textContext _localctx = new Literal_textContext(Context, State);
		EnterRule(_localctx, 10, RULE_literal_text);
		int _la;
		try {
			State = 59;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case SINGLE_QUOTE:
			case DOUBLE_QUOTE:
			case CHARACTER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==CHARACTER) {
					{
					State = 47;
					Match(CHARACTER);
					State = 48;
					literal_text();
					}
				}

				}
				break;
			case BACKSLASH:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 51;
				Match(BACKSLASH);
				State = 52;
				sequence();
				State = 53;
				literal_text();
				}
				}
				break;
			case RESERVED_SYMBOL:
				EnterOuterAlt(_localctx, 3);
				{
				{
				State = 55;
				Match(RESERVED_SYMBOL);
				State = 56;
				literal_text();
				}
				}
				break;
			case COMMA:
				EnterOuterAlt(_localctx, 4);
				{
				{
				State = 57;
				Match(COMMA);
				State = 58;
				literal_text();
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SequenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARACTER() { return GetToken(SuccinctCollectionSyntaxParser.CHARACTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RESERVED_SYMBOL() { return GetToken(SuccinctCollectionSyntaxParser.RESERVED_SYMBOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUOTE() { return GetToken(SuccinctCollectionSyntaxParser.QUOTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SuccinctCollectionSyntaxParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BACKSLASH() { return GetToken(SuccinctCollectionSyntaxParser.BACKSLASH, 0); }
		public SequenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sequence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.EnterSequence(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISuccinctCollectionSyntaxListener typedListener = listener as ISuccinctCollectionSyntaxListener;
			if (typedListener != null) typedListener.ExitSequence(this);
		}
	}

	[RuleVersion(0)]
	public SequenceContext sequence() {
		SequenceContext _localctx = new SequenceContext(Context, State);
		EnterRule(_localctx, 12, RULE_sequence);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 992L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,9,64,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,1,0,1,
		0,1,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,3,2,25,8,2,1,3,1,3,1,3,1,3,1,3,1,3,1,
		3,1,3,1,3,3,3,36,8,3,1,4,1,4,3,4,40,8,4,1,4,1,4,1,4,1,4,3,4,46,8,4,1,5,
		1,5,3,5,50,8,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,60,8,5,1,6,1,6,1,6,
		0,0,7,0,2,4,6,8,10,12,0,1,1,0,5,9,65,0,14,1,0,0,0,2,17,1,0,0,0,4,24,1,
		0,0,0,6,35,1,0,0,0,8,45,1,0,0,0,10,59,1,0,0,0,12,61,1,0,0,0,14,15,3,2,
		1,0,15,16,5,0,0,1,16,1,1,0,0,0,17,18,3,6,3,0,18,19,3,4,2,0,19,3,1,0,0,
		0,20,21,5,6,0,0,21,22,3,6,3,0,22,23,3,4,2,0,23,25,1,0,0,0,24,20,1,0,0,
		0,24,25,1,0,0,0,25,5,1,0,0,0,26,36,3,8,4,0,27,28,5,1,0,0,28,29,3,10,5,
		0,29,30,5,1,0,0,30,36,1,0,0,0,31,32,5,2,0,0,32,33,3,10,5,0,33,34,5,2,0,
		0,34,36,1,0,0,0,35,26,1,0,0,0,35,27,1,0,0,0,35,31,1,0,0,0,36,7,1,0,0,0,
		37,38,5,5,0,0,38,40,3,8,4,0,39,37,1,0,0,0,39,40,1,0,0,0,40,46,1,0,0,0,
		41,42,5,7,0,0,42,43,3,12,6,0,43,44,3,8,4,0,44,46,1,0,0,0,45,39,1,0,0,0,
		45,41,1,0,0,0,46,9,1,0,0,0,47,48,5,5,0,0,48,50,3,10,5,0,49,47,1,0,0,0,
		49,50,1,0,0,0,50,60,1,0,0,0,51,52,5,7,0,0,52,53,3,12,6,0,53,54,3,10,5,
		0,54,60,1,0,0,0,55,56,5,8,0,0,56,60,3,10,5,0,57,58,5,6,0,0,58,60,3,10,
		5,0,59,49,1,0,0,0,59,51,1,0,0,0,59,55,1,0,0,0,59,57,1,0,0,0,60,11,1,0,
		0,0,61,62,7,0,0,0,62,13,1,0,0,0,6,24,35,39,45,49,59
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
